<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FilterSeeder extends Seeder
{
    public function run(): void
    {
        // Optional: Clear existing records to avoid duplicates
        DB::table('filters')->truncate();

        $filters = [
            ['list_name' => 'yes_no', 'name' => 'yes', 'label' => 'Yes'],
            ['list_name' => 'field_status', 'name' => 'COMPLETED', 'label' => 'COMPLETED'],
            ['list_name' => 'field_status', 'name' => 'Not_Completed', 'label' => 'Not Completed'],
            ['list_name' => 'yes_no', 'name' => 'no', 'label' => 'No'],
            ['list_name' => 'weather', 'name' => 'fine', 'label' => 'Fine'],
            ['list_name' => 'weather', 'name' => 'windy', 'label' => 'Windy'],
            ['list_name' => 'weather', 'name' => 'rainy', 'label' => 'Rainy'],
            ['list_name' => 'security', 'name' => 'Safe', 'label' => 'لا يوجد عائق'],
            ['list_name' => 'security', 'name' => 'Unsafe', 'label' => 'يوجد عائق'],
            ['list_name' => 'visit_status', 'name' => 'not_visited', 'label' => 'Not visited لم يتم زيارة المبنى'],
            ['list_name' => 'visit_status', 'name' => 'partial_done', 'label' => 'Partial assessment completed تم عمل حصر جزئي'],
            ['list_name' => 'visit_status', 'name' => 'full_done', 'label' => 'Full assessment completed تم عمل الحصر بالكامل'],
            ['list_name' => 'building_damage_status', 'name' => 'fully_damaged', 'label' => 'Totally Damaged'],
            ['list_name' => 'building_damage_status', 'name' => 'partially_damaged', 'label' => 'Partially Damaged'],
            ['list_name' => 'building_damage_status', 'name' => 'committee_review', 'label' => 'Committee Review'],
            ['list_name' => 'unit_damage_Status', 'name' => 'fully_damaged2', 'label' => 'Totally Damaged'],
            ['list_name' => 'unit_damage_Status', 'name' => 'partially_damaged2', 'label' => 'Partially Damaged'],
            ['list_name' => 'unit_damage_Status', 'name' => 'committee_review2', 'label' => 'Committee Review'],
            ['list_name' => 'building_type', 'name' => 'house1', 'label' => 'House/منزل'],
            ['list_name' => 'building_type', 'name' => 'villa', 'label' => 'Villa/فيلا'],
            ['list_name' => 'building_type', 'name' => 'building', 'label' => 'Building/مبنى'],
            ['list_name' => 'building_type', 'name' => 'canopy', 'label' => 'Canopy/مظلة'],
            ['list_name' => 'building_type', 'name' => 'tower', 'label' => 'Tower/برج'],
            ['list_name' => 'building_type', 'name' => 'building_other', 'label' => 'Other/أخرى'],
            ['list_name' => 'building_material', 'name' => 'concrete', 'label' => 'Concrete'],
            ['list_name' => 'building_material', 'name' => 'metal', 'label' => 'Metal'],
            ['list_name' => 'building_material', 'name' => 'asbestos', 'label' => 'Asbestos'],
            ['list_name' => 'building_material', 'name' => 'wood', 'label' => 'Wood'],
            ['list_name' => 'building_material', 'name' => 'other_material', 'label' => 'Other'],
            ['list_name' => 'building_age', 'name' => 'years0_5', 'label' => '0-5 years'],
            ['list_name' => 'building_age', 'name' => 'years6_10', 'label' => '6-10 years'],
            ['list_name' => 'building_age', 'name' => 'years11_20', 'label' => '11-20 years'],
            ['list_name' => 'building_age', 'name' => 'years21_50', 'label' => '21-50 years'],
            ['list_name' => 'building_age', 'name' => 'years51_100', 'label' => '51-100 years'],
            ['list_name' => 'building_age', 'name' => 'years101more', 'label' => '101+ years'],
            ['list_name' => 'building_age', 'name' => 'not_sure', 'label' => 'Not sure'],
            ['list_name' => 'building_debris_qty', 'name' => 'Small', 'label' => 'Small (≤10 m³)'],
            ['list_name' => 'building_debris_qty', 'name' => 'Medium', 'label' => 'Medium (10–30 m³)'],
            ['list_name' => 'building_debris_qty', 'name' => 'Large', 'label' => 'Large (>30 m³)'],
            ['list_name' => 'yes_no_notsure', 'name' => 'yes3', 'label' => 'Yes'],
            ['list_name' => 'yes_no_notsure', 'name' => 'no3', 'label' => 'No'],
            ['list_name' => 'yes_no_notsure', 'name' => 'notsure3', 'label' => 'Not Sure'],
            ['list_name' => 'building_status_visit', 'name' => 'standing_partial_remove', 'label' => 'Standing but needs to be removed'],
            ['list_name' => 'building_status_visit', 'name' => 'removed', 'label' => 'Removed / تمت الإزالة'],
            ['list_name' => 'building_status_visit', 'name' => 'rubble', 'label' => 'Rubble / أنقاض'],
            ['list_name' => 'building_status_visit', 'name' => 'dangerous', 'label' => 'Dangerous / خطير'],
            ['list_name' => 'building_roof_type', 'name' => 'clay_tile', 'label' => 'Clay Tile / قرميد'],
            ['list_name' => 'building_roof_type', 'name' => 'concrete2', 'label' => 'Concrete / باطون'],
            ['list_name' => 'building_roof_type', 'name' => 'asbestos2', 'label' => 'Asbestos / اسبست'],
            ['list_name' => 'building_roof_type', 'name' => 'secorite', 'label' => 'Iron Sheets (Secorite) / صاج'],
            ['list_name' => 'building_roof_type', 'name' => 'other_roof', 'label' => 'Other / أخرى'],
            ['list_name' => 'building_use', 'name' => 'residential', 'label' => 'Residential / للسكن'],
            ['list_name' => 'building_use', 'name' => 'work', 'label' => 'Work / للعمل'],
            ['list_name' => 'building_use', 'name' => 'combined', 'label' => 'Combined / للعمل والسكن'],
            ['list_name' => 'building_ownership', 'name' => 'single', 'label' => 'Single owner / ملكية فردية'],
            ['list_name' => 'building_ownership', 'name' => 'multiple', 'label' => 'multiple owner / ملكية مشتركة'],
            ['list_name' => 'building_responsible', 'name' => 'owner', 'label' => 'Owner المالك'],
            ['list_name' => 'building_responsible', 'name' => 'board', 'label' => 'Board of management'],
            ['list_name' => 'building_responsible', 'name' => 'heirs', 'label' => 'Heirs (owner is deceased)'],
            ['list_name' => 'owner_status', 'name' => 'Owner_present', 'label' => 'Owner present / المالك موجود'],
            ['list_name' => 'owner_status', 'name' => 'Owner_captive', 'label' => 'Owner detained / المالك أسير'],
            ['list_name' => 'owner_status', 'name' => 'Owner_deceased', 'label' => 'Owner deceased المالك متوفى'],
            ['list_name' => 'owner_status', 'name' => 'Owner_missing', 'label' => 'Owner missing المالك مفقود'],
            ['list_name' => 'doc_type', 'name' => 'title_deed', 'label' => 'Title deed / Land registry'],
            ['list_name' => 'doc_type', 'name' => 'tax_record', 'label' => 'Tax record / سجل ضريبي'],
            ['list_name' => 'doc_type', 'name' => 'purchase_contract', 'label' => 'Purchase contract'],
            ['list_name' => 'doc_type', 'name' => 'rental_contract', 'label' => 'Rental contract'],
            ['list_name' => 'doc_type', 'name' => 'utility_bill', 'label' => 'Utility bill'],
            ['list_name' => 'doc_type', 'name' => 'other_doc', 'label' => 'Other / أخرى'],
            ['list_name' => 'doc_challenges', 'name' => 'lost', 'label' => 'Documents lost'],
            ['list_name' => 'doc_challenges', 'name' => 'access', 'label' => 'Difficulty accessing authorities'],
            ['list_name' => 'doc_challenges', 'name' => 'legal', 'label' => 'Legal issues'],
            ['list_name' => 'doc_challenges', 'name' => 'cost', 'label' => 'Financial cost'],
            ['list_name' => 'doc_challenges', 'name' => 'other_challenge', 'label' => 'Other / أخرى'],
            ['list_name' => 'dispute_types', 'name' => 'with_owner', 'label' => 'Dispute with another owner'],
            ['list_name' => 'dispute_types', 'name' => 'with_state', 'label' => 'Dispute with state'],
            ['list_name' => 'dispute_types', 'name' => 'boundary', 'label' => 'Boundary dispute'],
            ['list_name' => 'classification', 'name' => 'excellent', 'label' => 'الوضع ممتاز: أوراق كاملة'],
            ['list_name' => 'classification', 'name' => 'disputed', 'label' => 'متنازع عليها: خلاف مع ملاك آخر'],
            ['list_name' => 'classification', 'name' => 'missing_docs', 'label' => 'نقص مستندات: أوراق مفقودة'],
            ['list_name' => 'building_documents', 'name' => 'id2', 'label' => 'Id / صورة الهوية'],
            ['list_name' => 'building_documents', 'name' => 'ownership', 'label' => 'Ownership Document'],
            ['list_name' => 'building_documents', 'name' => 'permit', 'label' => 'Permit / رخصة'],
            ['list_name' => 'housing_unit_type', 'name' => 'basement', 'label' => 'بدروم / basement'],
            ['list_name' => 'housing_unit_type', 'name' => 'apartment', 'label' => 'شقة / apartment'],
            ['list_name' => 'housing_unit_type', 'name' => 'roof', 'label' => 'روف / roof'],
            ['list_name' => 'housing_unit_type', 'name' => 'warehouse', 'label' => 'حاصل / warehouse'],
            ['list_name' => 'agreement_type', 'name' => 'verbal', 'label' => 'Verbal شفهي'],
            ['list_name' => 'agreement_type', 'name' => 'written', 'label' => 'Written كتابي'],
            ['list_name' => 'service_status', 'name' => 'functional', 'label' => 'Functional سليم'],
            ['list_name' => 'service_status', 'name' => 'partially_damaged3', 'label' => 'Partially damaged'],
            ['list_name' => 'service_status', 'name' => 'fully_damaged3', 'label' => 'Fully damaged'],
            ['list_name' => 'damage_status', 'name' => 'no_damage', 'label' => 'No damage'],
            ['list_name' => 'damage_status', 'name' => 'damaged', 'label' => 'Damaged'],
            ['list_name' => 'infra_type2', 'name' => 'Housing', 'label' => 'Housing سكني'],
            ['list_name' => 'infra_type2', 'name' => 'Economic', 'label' => 'Economic اقتصادي'],
            ['list_name' => 'identity_type1', 'name' => 'idd', 'label' => 'ID هوية'],
            ['list_name' => 'identity_type1', 'name' => 'passport', 'label' => 'Passport جواز سفر'],
        ];

        DB::table('filters')->insert($filters);
    }
}
