<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoadFacilityFilterSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('road_facility_filters')->truncate();

        DB::table('road_facility_filters')->insert([
            ['list_name' => 'yes_no', 'name' => 'yes', 'label' => 'Yes', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'yes_no', 'name' => 'no', 'label' => 'No', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'security', 'name' => 'Safe', 'label' => '?? ???? ????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'security', 'name' => 'Unsafe', 'label' => '???? ????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'water_network', 'label' => 'Water network', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'sewer_network', 'label' => 'Sewer network', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'storm_water_network', 'label' => 'Storm water network', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'water_well', 'label' => 'Water Well', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'water_desalination_plant', 'label' => 'Water desalination plant', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'water_reservoirs', 'label' => 'Water reservoirs', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'wwtp', 'label' => 'WWTP', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'water_pumping_station', 'label' => 'Water Pumping station', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'sewage_pumping_station', 'label' => 'Sewage Pumping station', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'storm_water_pumping_station', 'label' => 'Storm water pumping station', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'solid_waste_transfer_station', 'label' => 'Solid waste transfer station', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'cmwu_stores', 'label' => 'CMWU Stores', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'infra_type', 'name' => 'other_infra', 'label' => 'Other (Specify)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'governorate', 'name' => 'North', 'label' => 'North', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'governorate', 'name' => 'Gaza', 'label' => 'Gaza', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'governorate', 'name' => 'Middle_Area', 'label' => 'Middle Area', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'governorate', 'name' => 'Khan_Younis', 'label' => 'Khan Younis', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'governorate', 'name' => 'Rafah', 'label' => 'Rafah', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Um_AlNasser', 'label' => 'Um_AlNasser', 'group_value' => 'North', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Bait_Hanoun', 'label' => 'Bait_Hanoun', 'group_value' => 'North', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Jabalia', 'label' => 'Jabalia', 'group_value' => 'North', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Bait_Lahia', 'label' => 'Bait_Lahia', 'group_value' => 'North', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Gaza', 'label' => 'Gaza', 'group_value' => 'Gaza', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Juhr_Aldeek', 'label' => 'Juhr_Aldeek', 'group_value' => 'Gaza', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Almughraqa', 'label' => 'Almughraqa', 'group_value' => 'Gaza', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Alzahra', 'label' => 'Alzahra', 'group_value' => 'Gaza', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'AlNusairat', 'label' => 'AlNusairat', 'group_value' => 'Middle_Area', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Alburaje', 'label' => 'Alburaje', 'group_value' => 'Middle_Area', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'AlMaghazi', 'label' => 'AlMaghazi', 'group_value' => 'Middle_Area', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'AlMusadar', 'label' => 'AlMusadar', 'group_value' => 'Middle_Area', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Wadi_Alsalqa', 'label' => 'Wadi_Alsalqa', 'group_value' => 'Middle_Area', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Dair_Albalah', 'label' => 'Dair_Albalah', 'group_value' => 'Middle_Area', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Alzawayda', 'label' => 'Alzawayda', 'group_value' => 'Middle_Area', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Khanyounis', 'label' => 'Khanyounis', 'group_value' => 'Khan_Younis', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Alqarara', 'label' => 'Alqarara', 'group_value' => 'Khan_Younis', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Bani_Sohaila', 'label' => 'Bani_Sohaila', 'group_value' => 'Khan_Younis', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Abasan_AlJadida', 'label' => 'Abasan_AlJadida', 'group_value' => 'Khan_Younis', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Abasan_alkabeira', 'label' => 'Abasan_alkabeira', 'group_value' => 'Khan_Younis', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Khuzaa', 'label' => 'Khuzaa', 'group_value' => 'Khan_Younis', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'AlFukhari', 'label' => 'AlFukhari', 'group_value' => 'Khan_Younis', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'Rafah', 'label' => 'Rafah', 'group_value' => 'Rafah', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'AlNasser', 'label' => 'AlNasser', 'group_value' => 'Rafah', 'sort_order' => null],
            ['list_name' => 'locality', 'name' => 'AlShuka', 'label' => 'AlShuka', 'group_value' => 'Rafah', 'sort_order' => null],
            ['list_name' => 'type_damage', 'name' => 'Completely', 'label' => 'Completely', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'type_damage', 'name' => 'partially', 'label' => 'Partially', 'group_value' => '1', 'sort_order' => null],
            ['list_name' => 'weather', 'name' => 'fine', 'label' => 'Fine', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'weather', 'name' => 'windy', 'label' => 'Windy', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'weather', 'name' => 'rainy', 'label' => 'Rainy', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'damage_cause', 'name' => 'direct_attack', 'label' => 'Direct attack', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'damage_cause', 'name' => 'indirect_attack', 'label' => 'Indirect attack', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'damage_cause', 'name' => 'other_cause', 'label' => 'Other (specify)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'unit', 'name' => 'cube_meter__m3', 'label' => 'Cube Meter (m3)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'unit', 'name' => 'square_meter__m2', 'label' => 'Square Meter (m2)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'unit', 'name' => 'run_meter__m', 'label' => 'Run Meter (m)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'unit', 'name' => 'liter', 'label' => 'Liter', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'unit', 'name' => 'no', 'label' => 'No.', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'unit', 'name' => 'kilogram__kg', 'label' => 'Kilogram (Kg)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'unit', 'name' => 'ton__t', 'label' => 'Ton (t)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'unit', 'name' => 'other_unit', 'label' => 'Other', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'provider_response', 'name' => 'none', 'label' => 'None', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'provider_response', 'name' => 'temporary_repairs', 'label' => 'Temporary repairs', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'provider_response', 'name' => 'permanent_repairs', 'label' => 'Permanent repairs', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pipe_type', 'name' => 'steel', 'label' => 'Steel', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pipe_type', 'name' => 'concrete', 'label' => 'Concrete', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pipe_type', 'name' => 'upvc', 'label' => 'UPVC', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pipe_type', 'name' => 'hdpe', 'label' => 'HDPE', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pipe_type', 'name' => 'ductile_iron', 'label' => 'Ductile iron', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pipe_type', 'name' => 'other_pipe', 'label' => 'Other (specify)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'control_valve', 'label' => 'Control valve', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'magnetic_valve', 'label' => 'Magnetic Valve', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'water_meter', 'label' => 'Water meter', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'elbow', 'label' => 'Elbow', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'strainer', 'label' => 'Strainer', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'pressure_reducing_valve', 'label' => 'Pressure Reducing Valve', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'air_release_valve', 'label' => 'Air Release Valve', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'water_manhole', 'label' => 'Water Manhole', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'sewer_manhole', 'label' => 'Sewer Manhole', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'storm_water_manhole', 'label' => 'Storm water Manhole', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'storm_water__culvert', 'label' => 'Storm water culvert', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'fittings', 'name' => 'other_fittings', 'label' => 'Other (Specify)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'reinstatement_type', 'name' => 'asphalt', 'label' => 'Asphalt', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'reinstatement_type', 'name' => 'tiles', 'label' => 'Tiles', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'reinstatement_type', 'name' => 'dirt_road', 'label' => 'Dirt road', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'reinstatement_type', 'name' => 'other_reinstatement', 'label' => 'Other (Specify)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'asphalt', 'label' => 'Asphalt ???? ???????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'basecoarse', 'label' => 'basecoarse ???? ???????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'concrete', 'label' => 'Concrete ??????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'street_interlock', 'label' => 'Street Interlock ??????? ???????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'sidewalk_interlock', 'label' => 'Sidewalk ???????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'curbstone', 'label' => 'Curbstone ??? ????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'unpaved_road', 'label' => 'Unpaved Road ???? ????? ?? ?????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'lighting_electrical_network', 'label' => 'Lighting Electrical Network ???? ?????? ???????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'lighting_poles', 'label' => 'Lighting Poles ????? ?????? ???????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'electricity_distribution_network', 'label' => '???? ???????? (??? ????/?????) Electricity distribution network', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'stormwater', 'label' => 'Surface stormwater drainage ????? ???? ???????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'traffic_signs', 'label' => 'Traffic signs & road furniture ???????? ????????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'demolition_works', 'label' => 'Demolition Works ????? ???????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'Handrails', 'label' => 'Handrails ?????????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'road_painting', 'label' => 'Road Painting ????? ?????? ?????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_type', 'name' => 'other_component', 'label' => 'Other ????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pole_type', 'name' => 'wooden_pole', 'label' => 'Wooden Pole ???? ????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pole_type', 'name' => 'steel_pole', 'label' => 'Steel Pole ???? ?????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pole_type', 'name' => 'other_pole', 'label' => 'Other ????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'network_type', 'name' => 'water_network', 'label' => 'Water Network ???? ????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'network_type', 'name' => 'sewage_network', 'label' => 'Sewage Network ???? ??? ???', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'network_type', 'name' => 'storm_water', 'label' => 'Storm Water Network ???? ????? ???? ?????', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'network_item', 'name' => 'pipe', 'label' => 'Pipe', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'network_item', 'name' => 'fittings', 'label' => 'Fittings', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'network_item', 'name' => 'reinstatement', 'label' => 'Reinstatement Works', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_damage_level', 'name' => 'minor', 'label' => 'Minor damage (road usable)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_damage_level', 'name' => 'moderate', 'label' => 'Moderate damage (partial use / needs maintenance)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_damage_level', 'name' => 'severe', 'label' => 'Severe damage (not usable)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_damage_level', 'name' => 'destroyed', 'label' => 'Totally destroyed', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_damage_level', 'name' => 'No_Damage', 'label' => 'No Damage', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_access', 'name' => 'open', 'label' => 'Fully open', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_access', 'name' => 'partial', 'label' => 'Partially open', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'road_access', 'name' => 'closed', 'label' => 'Fully closed', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'blockage_reason', 'name' => 'landfill', 'label' => 'Backfill / excavation', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'blockage_reason', 'name' => 'debris', 'label' => 'Debris / rubble', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'blockage_reason', 'name' => 'poles', 'label' => 'Fallen poles', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'blockage_reason', 'name' => 'uxo', 'label' => 'Security risk (UXO)', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'lane_count', 'name' => 'one', 'label' => 'One lane', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'lane_count', 'name' => 'two', 'label' => 'Two lanes', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'lane_count', 'name' => 'more', 'label' => 'More than two', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'sidewalk_damage_type', 'name' => 'broken_tiles', 'label' => 'Broken tiles', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'sidewalk_damage_type', 'name' => 'missing_tiles', 'label' => 'Missing tiles', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'sidewalk_damage_type', 'name' => 'collapsed_sidewalk', 'label' => 'Collapsed sidewalk', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'sidewalk_damage_type', 'name' => 'pwd_ramps_damaged', 'label' => 'Damaged accessibility ramps', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'sidewalk_damage_type', 'name' => 'pedestrian_obstacles', 'label' => 'Pedestrian obstacles', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'traffic_signs_type', 'name' => 'guide', 'label' => 'Guide signs', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'traffic_signs_type', 'name' => 'warning', 'label' => 'Warning signs', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'traffic_signs_type', 'name' => 'traffic_light', 'label' => 'Traffic lights', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'traffic_signs_type', 'name' => 'mirrors', 'label' => 'Intersection mirrors', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'traffic_signs_type', 'name' => 'speed_bumps', 'label' => 'Speed bumps', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'traffic_signs_type', 'name' => 'other', 'label' => 'Other', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'demolition_type', 'name' => 'whole', 'label' => 'Whole', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'demolition_type', 'name' => 'partial', 'label' => 'Partially', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'demolition_type', 'name' => 'no_need', 'label' => 'No need', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pole_material', 'name' => 'galvanized', 'label' => 'Galvanized steel pole', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'pole_material', 'name' => 'wooden', 'label' => 'Wooden pole', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'voltage_level', 'name' => 'low', 'label' => 'Low voltage', 'group_value' => null, 'sort_order' => null],
            ['list_name' => 'voltage_level', 'name' => 'high', 'label' => 'High voltage', 'group_value' => null, 'sort_order' => null],
        ]);
    }
}
