DROP TABLE IF EXISTS `assessments`;

CREATE TABLE `assessments` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(512),
    `label` VARCHAR(512),
    `hint` VARCHAR(512),
    `criteria` VARCHAR(512) NULL,
    `type` VARCHAR(512) NULL
);

INSERT INTO
    `assessments` (`name`, `label`, `hint`, `criteria`, `type`)
VALUES
    ('attachments', 'Attachments', 'المرفقات', NULL, '0'),
    ('owner_name', 'Owner Name', 'اسم المالك', NULL, '0'),
    ('field_status', 'Assessment Status', 'حالة الإستبيان', NULL, '0'),
    ('parcel_no1', 'رقم القسيمة', '', NULL, '0'),
    ('block_no1', 'رقم القطعة', '', NULL, '0'),
    ('owner_na', 'القطعة/ قسيمة', '', NULL, '0'),
    ('units_count', 'عدد الوحدات', '', NULL, '0'),
    ('assignedto', 'اسم الباحث', '', NULL, '0'),
    ('groupnumber', 'رقم المجموعة', '', NULL, '0'),
    ('zone_code', 'رقم الزون', '', NULL, '0'),
    ('objectid', 'objectid', 'رقم المبنى', NULL, '0'),
    ('start', 'start', '', NULL, '0'),
    ('end', 'end', '', NULL, '0'),
    ('today', 'today', '', NULL, '0'),
    ('username', 'username', '', NULL, '0'),
    ('simserial', 'simserial', '', NULL, '0'),
    ('g0', 'introduction', '', NULL, '0'),
    ('weather', 'weather', 'حال الطقس', NULL, '0'),
    ('security_situation', 'security situation', 'هل يوجد عائق يمنع عملية الحصر', NULL, '0'),
    ('security_info', 'security information', 'ما هو العائق', NULL, '0'),
    ('g1', 'current damage status', '', NULL, '0'),
    ('building_damage_status', 'what is the current damage status of the building?', 'ما هي حالة الضرر الحالية للمبنى؟', NULL, '0'),
    ('building_information', 'building information', 'معلومات المبنى', NULL, '0'),
    ('bldng_introduction', '1. introduction', '1. مقدمة', NULL, '0'),
    ('building_type', '1.1 building type', 'نوع المبنى', NULL, '0'),
    ('building_type_other', '1.1.1  building type', 'اكتب نوع المبنى', NULL, '0'),
    ('building_use', '1.2 building use', 'نوع استخدام المبنى', NULL, '0'),
    ('building_name', '1.3 building name', 'اسم المبنى. مثال: برج فلسطين', NULL, '0'),
    ('date_of_damage', '1.4 date of damage', 'تاريخ القصف/الضرر', NULL, '0'),
    ('building_material', '1.5 type/material of building', 'نوع مادة المبنى', NULL, '0'),
    ('other_material', '1.5.1 if other, specify:', 'إذا تم اختيار آخر/أخرى في السؤال السابق، وضح الإجابة', NULL, '0'),
    ('building_age', '1.6 how old is  the building?', 'كم هو عمر المبنى؟', NULL, '0'),
    ('floor_nos', '1.7 number of floors', 'عدد الطوابق', NULL, '0'),
    ('ground_floor_area__m2', '1.8 ground floor area (m2)', 'مساحة الطابق الأرضي (م2)', NULL, '0'),
    ('floor_area_m2', '1.9 floor area (m2)', 'مساحة الطابق المتكرر', NULL, '0'),
    ('units_nos', '1.10 number of units', 'عدد الوحدات', NULL, '0'),
    ('damaged_units_nos', '1.11 number of targeted damaged units', 'عدد الوحدات المتضررة', NULL, '0'),
    ('occupied_units_nos', '1.12 number of occupied units', 'عدد الوحدات المأهولة', NULL, '0'),
    ('vacant_units_nos', '1.13 number of vacant units', 'عدد الوحدات الفارغة', NULL, '0'),
    ('is_damaged_before', '1.14 prior to the event, did the building have some damage due to previous conflicts or other reasons?', 'هل تضرر المبنى قبل الأحداث الحالية بسبب صراع آخر أو أسباب أخرى؟', NULL, '0'),
    ('if_damaged', '1.14.1 if yes, specify when and how?', 'إذا تضرر المبنى قبل ذلك، حدد متى وكيف؟', NULL, '0'),
    ('building_debris_exist', '1.15 is there debris generated at the building level?', 'هل يوجد ركام ناتج عن الضرر في المبنى؟', NULL, '0'),
    ('building_debris_qty', '1.15.1 estimated amount of debris at building level', 'تقدير كمية الركام في المبنى', NULL, '0'),
    ('building_debris_blocking', '1.15.2 does debris obstruct access or use of the building?', 'هل الركام يعيق الوصول أو الاستخدام؟', NULL, '0'),
    ('uxo_present', '1.16 are there any uxo present?', 'هل يوجد مخلفات حربية / ذخائر غير منفجرة داخل المبنى؟', NULL, '0'),
    ('bodies_present', '1.17 are there any bodies in the building?', 'هل يوجد جثث داخل المبنى؟', NULL, '0'),
    ('estimated_number_of_bodies', '1.17.1 estimated number of bodies', 'عدد الجثث (تقديري)', NULL, '0'),
    ('building_status_visit', '1.18 building status at the time of visit', 'حالة المبنى وقت المعاينة', NULL, '0'),
    ('building_roof_type', '1.19 building roof type', 'نوع سطح المبنى', NULL, '0'),
    ('clay_tile_area', '1.19.1 clay tile roof area (m2)', 'مساحة القرميد (م2)', NULL, '0'),
    ('concrete_area', '1.19.2 concrete roof area (m2)', 'مساحة الباطون (م2)', NULL, '0'),
    ('aspestos_area', '1.19.3 aspestos roof area (m2)', 'مساحة الاسبست (م2)', NULL, '0'),
    ('scorite_area', '1.19.4 scorite roof area (m2)', 'مساحة الصاج (م2)', NULL, '0'),
    ('other_roof', '1.19.5 if other, specify roof type', 'في حال أخرى، حدد نوع السقف', NULL, '0'),
    ('other_roof_area', '1.19.6 specify other roof area (m2)', 'في حال أخرى،  حدد المساحة (م2)', NULL, '0'),
    ('ownweship_information', '2. ownership information', ' 2. معلومات عن الملكية', NULL, '0'),
    ('ownweshipbldng_introduction', '2.1 introduction', '2.1 معلومات عن ملكية المبنى', NULL, '0'),
    ('building_ownership', '2.1.1 building ownership', 'اختر نوع الملكية', NULL, '0'),
    ('owner_status', '2.1.2 what is the status of the property owner?', 'ما هو وضع مالك العقار؟', NULL, '0'),
    ('building_responsible', '2.1.3 who is responsible for the building?', 'من المسؤول عن البناية؟', NULL, '0'),
    ('building_authorization', '2.1.4 do you have authorization/delegation to manage the building and request compensation (e.g., power of attorney)?', 'هل لديك تفويض بإدارة المبنى وطلب التعويضات؟', NULL, '0'),
    ('land_fully_owned', '2.1.5 is the land fully owned?', 'هل الأرض مملوكة بالكامل؟', NULL, '0'),
    ('owner_name', '2.1.6 owner full name', 'اسم المالك', NULL, '0'),
    ('owner_id', '2.1.7 owner id number', 'رقم هوية المالك', NULL, '0'),
    ('owner_mobile', '2.1.8 owner mobile number', 'رقم جوال المالك', NULL, '0'),
    ('board1_name', '2.1.9 board member 1 full name', 'إسم رئيس مجلس الإادارة', NULL, '0'),
    ('board1_id', '2.1.10 board member 1 id number', 'رقم الهاتف المحمول', NULL, '0'),
    ('board1_number', '2.1.11 board member 2 id number', 'رقم الهوية', NULL, '0'),
    ('board2_name', '2.1.12 board member 2 full name', 'إسم نائب مجلس الإادارة', NULL, '0'),
    ('board2_id', '2.1.13 board member 2 id number', 'رقم الهاتف المحمول', NULL, '0'),
    ('board2_number', '2.1.14 board member 2 id number', 'رقم الهوية', NULL, '0'),
    ('has_authorization_if_not_owner', '2.1.15 if not fully owned, do you have authorization/delegation to manage the property (e.g., power of attorney)?', 'إذا لم تكن الملكية كاملة، هل لديك تفويض/وكالة لإدارة العقار؟', NULL, '0'),
    ('authorization_details', '2.1.16 please specify the authorization (optional)', 'يرجى توضيح نوع التفويض (اختياري)', NULL, '0'),
    ('is_rented', '2.1.17 is the property rented?', 'هل العقار مستأجر بالكامل؟', NULL, '0'),
    ('tenant_names', '2.1.18 tenant names (optional)', 'أسماء المستأجرين (اختياري)', NULL, '0'),
    ('agreement_type', '2.1.19 type of agreement', 'نوع الاتفاق', NULL, '0'),
    ('agreement_duration', '2.1.20 agreement duration', 'مدة الاتفاق', NULL, '0'),
    ('documents', '2.2 documents', '2.2 الوثائق', NULL, '0'),
    ('has_documents', '2.2.1 are ownership documents available?', 'هل تتوفر مستندات تثبت الملكية؟', NULL, '0'),
    ('doc_types_available', '2.2.2 which documents are available?', 'ما هي المستندات المتوفرة؟', NULL, '0'),
    ('doc_types_other', '2.2.3 please specify other documents', 'يرجى تحديد مستندات أخرى', NULL, '0'),
    ('no_documents_reason', '2.2.4 if no, briefly explain why (optional)', 'إذا لا، وضّح السبب (اختياري)', NULL, '0'),
    ('need_renew_docs', '2.2.5 do you need to renew or obtain documents?', 'هل تحتاج إلى تجديد أو استخراج مستندات؟', NULL, '0'),
    ('doc_challenges', '2.2.6 main challenges (if any)', 'التحديات الرئيسية (إن وجدت)', NULL, '0'),
    ('doc_challenges_other', '2.2.7 please specify (other)', 'يرجى التحديد (أخرى)', NULL, '0'),
    ('disputes', '2.3 disputes', '2.3 النزاعات', NULL, '0'),
    ('has_dispute', '2.3.1 are there any known disputes?', 'هل توجد نزاعات معروفة على العقار أو الأرض؟', NULL, '0'),
    ('dispute_types', '2.3.2 type of dispute', 'نوع النزاع', NULL, '0'),
    ('dispute_other', '2.3.3 please specify other dispute', 'يرجى تحديد نزاع آخر', NULL, '0'),
    ('building_attachment', '3. building attachments', '3. مرفقات المبنى', NULL, '0'),
    ('attach_one_photo_for_each_of_the_following_documents', '410', 'یرفق ما أمكن صورة عن كل من المستندات التالیة', NULL, '0'),
    ('select_document', '3.3 select one or more of the following documents to be attached', 'اختر المستندات المرفقة', NULL, '0'),
    ('id_number_photo', '3.4 id number', 'صورة الهوية', NULL, '0'),
    ('land_ownership_photo', '3.5 land ownership', 'صورة إثبات ملكية الأرض', NULL, '0'),
    ('municipal_permit_photo', '3.6 municipal permit', 'صورة رخصة البلدية', NULL, '0'),
    ('other_documents_photo', '3.7 other documents', 'صورة مستندات أخرى', NULL, '0'),
    ('building_services', '4. building services', '4. خدمات العمارة', NULL, '0'),
    ('has_elevator', '4.1 is there an elevator?', 'هل يوجد مصعد في العمارة/ البناية؟', NULL, '0'),
    ('elevator_number', '4.2 number of elevators', 'عدد المصاعد', NULL, '0'),
    ('elevator_status', '4.2.1 elevator condition', 'حالة المصعد', NULL, '0'),
    ('elevator_box', '4.2.2 cabin condition', 'حالة الكابينة', NULL, '0'),
    ('elevator_motor', '4.2.3 motor condition', 'حالة الماتور', NULL, '0'),
    ('has_solar', '4.3 is there a solar energy system?', 'هل يوجد نظام طاقة شمسية في البناية؟', NULL, '0'),
    ('solar_damage_status', '4.3.1 solar system condition', 'حالة نظام الطاقة الشمسية', NULL, '0'),
    ('has_well', '4.4 is there a well and submersible pump system?', 'هل يوجد بئر مياه ونظام غاطس؟', NULL, '0'),
    ('well_damage_status', '4.4.1 well system condition', 'حالة نظام البئر/الغاطس', NULL, '0'),
    ('has_fence', '4.5 is there a building fence?', 'هل يوجد سور للبناية؟', NULL, '0'),
    ('fence_damage_status', '4.5.1 fence condition', 'حالة السور', NULL, '0'),
    ('fence_length', '4.5.2 fence length', 'طول السور (متر)', NULL, '0'),
    ('has_electric_room', '4.6 is there an electrical room?', 'هل توجد غرفة كهرباء؟', NULL, '0'),
    ('electric_room_damage_status', '4.6.1 electrical room condition', 'حالة غرفة الكهرباء', NULL, '0'),
    ('has_sewage', '4.7 is there a sewage system?', 'هل يوجد نظام صرف صحي؟', NULL, '0'),
    ('sewage_damage_status', '4.7.1 sewage system condition', 'حالة الصرف الصحي', NULL, '0'),
    ('service_ownership', '4.8 service ownership', 'اختر ملكية الخدامات', NULL, '0'),
    ('service_ownership_name', '4.8.1 service ownership name', 'ما اسم مالك الخدمات', NULL, '0'),
    ('has_other_service', '4.9 other building service?', 'خدمة أخرى خاصة بالعمارة؟', NULL, '0'),
    ('other_service_details', '4.9.1 specify the service and damage (if any)', 'حدّد المرفق ونوع الضرر إن وجد', NULL, '0'),
    ('building_services_notes', '4.10 comments on building services', 'ملاحظات حول خدمات العمارة', NULL, '0'),
    ('bldng_accessories', '5. building accessories', '5. ملحقات المبنى', NULL, '0'),
    ('staircase_status', '5.1 staircase condition', 'حالة الدرج', NULL, '0'),
    ('staircase_widt', '5.1.1 staircase width (meters)', 'عرض الدرج (متر)', NULL, '0'),
    ('has_parking', '5.2 is there a garage/parking?', 'هل يوجد كراج؟', NULL, '0'),
    ('parking_status', '5.2.1 garage condition', 'حالة الكراج', NULL, '0'),
    ('garage_area', '5.2.2 garage area (m²)', 'مساحة الكراج (م²)', NULL, '0'),
    ('garage_type', '5.2.3 garage type', 'نوع الكراج', NULL, '0'),
    ('has_canopy', '5.3 is there a canopy?', 'هل توجد مظلة؟', NULL, '0'),
    ('canopy_status', '5.3.1 canopy condition', 'حالة المظلة', NULL, '0'),
    ('carport_length', '5.3.2 canopy length (m)', 'طول المظلة (م)', NULL, '0'),
    ('carport_width', '5.3.3 canopy width (m)', 'عرض المظلة (م)', NULL, '0'),
    ('carport_height', '5.3.4 canopy height (m)', 'ارتفاع المظلة (م)', NULL, '0'),
    ('has_basement', '5.4 is there a basement?', 'هل يوجد بدروم؟', NULL, '0'),
    ('basement_status', '5.4.1 basement condition', 'حالة البدروم', NULL, '0'),
    ('basement_area', '5.4.2 basement area (m²)', 'مساحة البدروم (م²)', NULL, '0'),
    ('has_mezzanine', '5.5 is there a mezzanine?', 'هل توجد سدة؟', NULL, '0'),
    ('mezzanine_status', '5.5.1 mezzanine condition', 'حالة السدة', NULL, '0'),
    ('roof_terrace_area', '5.5.2 roof terrace area (m²)', 'مساحة السدة (م²)', NULL, '0'),
    ('bldng_engineer_comments', '6. engineer comments', '6. ملاحظات المهندس', NULL, '0'),
    ('comments_recommendations', '6.1  comments & recommendations', 'اشرح بشكل عام مواصفات المبنى وسجل أي ملاحظات أخرى', NULL, '0'),
    ('building_image', '6.2  take picture for the whole building', 'خذ صورة عامة لكل المبنى', NULL, '0'),
    ('building_image2', '6.3  take picture for the whole building', 'خذ صورة عامة أخرى لكل المبنى', NULL, '0'),
    ('break01_note', 'the following page will ask you if you want to add a damaged unit. please click "add" to add information for a new damaged unit in this building.', 'تنويه: في الخانة التالية، قم بتعبئة بيانات الوحدات المتضررة في هذا المبنى. عندما تنتهي من إضافة بيانات الوحدة ، قم بالضغط على إشارة +  لإضافة وحدة سكنية. كرر العملية عند اللزوم وذلك حسب عدد الوحدات المتضررة في المبنى.', NULL, '0'),
    ('housing_unit', 'housing unit وحدة سكنية', '', NULL, '0'),
    ('housing_unit_group', '7. unit introduction', '7. الوحدة السكنية', NULL, '0'),
    ('housing_unit_type', '7.1 housing unit type', 'نوع الوحدة السكنية', NULL, '0'),
    ('unit_damage_status', '7.2 unit damage status', 'حالة الضرر', NULL, '0'),
    ('page8', '8. unit information', '8. معلومات الوحدة السكنية', NULL, '0'),
    ('floor_number', '8.1  floor number', 'حدد رقم الطابق الذي يوجد فيها الوحدة المتضررة', NULL, '0'),
    ('housing_unit_number', '8.2 housing unit number', ' رقم الوحدة السكنية', NULL, '0'),
    ('unit_direction', '8.3 specify the direction of the damaged unit', ' حدد اتجاه الوحدة المتضررة', NULL, '0'),
    ('damaged_area_m2', '8.4 damaged unit area - m2', 'مساحة الوحدة المتضررة', NULL, '0'),
    ('infra_type2', '8.5 unit use', 'نوع استخدام الوحدة المتضررة', NULL, '0'),
    ('house_unit_ownership', '8.6  house unit ownership', 'نوع ملكية الوحدة المتضررة', NULL, '0'),
    ('other_ownership', '8.7  if other, specify:', 'إذا تم اختيار آخر/أخرى في السؤال السابق، وضح الإجابة', NULL, '0'),
    ('occupied', '8.8  occupied before conflict?', 'هل كانت الوحدة المتضررة مشغولة قبل الحدث/القصف؟', NULL, '0'),
    ('number_of_rooms', '8.9 number of rooms', ' عدد الغرف', NULL, '0'),
    ('page9', '9. household and unit information', '9. معلومات  الأسرة والوحدة السكنية', NULL, '0'),
    ('identity_type1', '9.0 identity type', 'نوع الوثيقة', NULL, '0'),
    ('id_number1', '9.1 id number', 'رقم الهوية', NULL, '0'),
    ('passport1', '9.2 passport number', 'رقم الجواز', NULL, '0'),
    ('other_id1', '9.2.1 if other, specify', 'في حال اخترت أخرى، حدد نوع الوثيقة ورقمها', NULL, '0'),
    ('unit_owner', '9.3 unit owner', 'اسم مالك الوحدة', NULL, '0'),
    ('q_9_3_1_first_name', '9.3.1 first name', 'الاسم الأول', NULL, '0'),
    ('q_9_3_2_second_name__father', '9.3.2 second name (father)', 'اسم الأب', NULL, '0'),
    ('q_9_3_3_third_name__grandfather', '9.3.3 third name (grandfather)', 'اسم الجد', NULL, '0'),
    ('q_9_3_4_last_name', '9.3.4 last name', 'اسم العائلة', NULL, '0'),
    ('sex', '9.4 gender', 'جنس المالك', NULL, '0'),
    ('mobile_number', '9.5  mobile number', 'رقم الموبايل. اكتب رقم الموبايل بالشكل التالي: 0592797072', NULL, '0'),
    ('additional_mobile', '9.5.1 additional mobile number', 'رقم موبايل اضافي. اكتب رقم الموبايل بالشكل التالي: 0592797073', NULL, '0'),
    ('owner_job', '9.6 job', 'وظيفة المالك', NULL, '0'),
    ('other_job', '9.6.1 if other, specify', 'إذا تم اختيار آخر/أخرى في السؤال السابق، وضح الإجابة', NULL, '0'),
    ('age', '9.7  age', 'عمر المالك', NULL, '0'),
    ('marital_status', '9.8 marital status', 'الحالة الاجتماعية للمالك', NULL, '0'),
    ('ownership_image', '9.9 take picture for the id and other documents', 'خذ صورة للهوية وإثبات الملكية', NULL, '0'),
    ('page10', '10. spouses and disability information', '10. معلومات الأزواج وذوي الإعاقة', NULL, '0'),
    ('no_spouses', '10.1 number of spouses', 'عدد الزوجات', NULL, '0'),
    ('spouse1', '10.2 spouse name', ' اسم الزوج/الزوجة', NULL, '0'),
    ('spouse1_id', '10.3 spouse id', 'رقم هوية الزوج/الزوجة', NULL, '0'),
    ('spouse2', '10.4 second spouse name', ' الزوجة الثانية', NULL, '0'),
    ('spouse2_id', '10.5 second spouse id', 'رقم هوية الزوجة الثانية', NULL, '0'),
    ('spouse3', '10.6 third spouse name', 'الزوجة الثالثة', NULL, '0'),
    ('spouse3_id', '10.7 third spouse id', 'رقم هوية الزوجة الثالثة', NULL, '0'),
    ('spouse4', '10.8 fourth spouse name', 'الزوجة الرابعة', NULL, '0'),
    ('spouse4_id', '10.9 fourth spouse id', 'رقم هوية الزوجة الرابعة', NULL, '0'),
    ('are_there_people_with_disability', '10.10 are there people with disability?', 'هل يوجد أحدا من ذوي الإعاقة؟', NULL, '0'),
    ('number_of_people_with_disability', '10.11 number of people with disability', 'عدد الأشخاص من ذوي الإعاقة', NULL, '0'),
    ('handicapped_type', '10.12 type of disability', 'نوع الإعاقة', NULL, '0'),
    ('other_handicapped', '10.13 if other, specify:', 'إذا تم اختيار آخر/أخرى في السؤال السابق، وضح الإجابة', NULL, '0'),
    ('is_refugee', '10.14 is the family registered as refugee?', 'العائلة مسجلة كلاجئة مع الأونروا', NULL, '0'),
    ('unrwa_registration_number', '10.15  write the unrwa registration number', 'رقم بطاقة الاونروا الجدید/القدیم', NULL, '0'),
    ('page11', '11. family size', '11.عدد أفراد الأسرة', NULL, '0'),
    ('number_of_nuclear_families', '11.1 number of nuclear families', 'عدد الأسر النووية', NULL, '0'),
    ('mchildren_001', '11.2 no. males (<18 years old)', 'عدد الذكور ممن هم أقل من 18 عاما.', NULL, '0'),
    ('myoung', '11.3 no. males (>=18 and < 60 years old)', 'عدد الذكور ممن هم 18 عاما أو أكبر وأقل من 60 عاما.', NULL, '0'),
    ('melderly', '11.4 no. males (>=60 years old)', 'عدد الذكور ممن هم أكبر من 60 عاما.', NULL, '0'),
    ('fchildren', '11.5 no. females (<18 years old)', 'عدد الإناث ممن هم أقل من 18 عاما.', NULL, '0'),
    ('fyoung_001', '11.6 no. females (>=18 and < 60 years old)', 'عدد الإناث ممن هم 18 عاما أو أكبر وأقل من 60 عاما.', NULL, '0'),
    ('felderly', '11.7 no. females (>=60 years old)', 'عدد الإناث ممن هم أكبر من 60 عاما.', NULL, '0'),
    ('pregnant', '11.8 no. pregnant women', 'عدد النساء الحوامل', NULL, '0'),
    ('lactating', '11.9 no. lactating women', 'عدد النساء المرضعات', NULL, '0'),
    ('page12', '12. current residence and refugee status', '12. مكان الإقامة الحالي وحالة اللجوء', NULL, '0'),
    ('the_unit_resident', '12.0 the unit resident at the time of damage is', ' المقیم في المنزل وقت الضرر', NULL, '0'),
    ('current_address', '12.1 is the current address as same as the original address?', 'هل العنوان الحالي هو نفس العنوان الأصلي (عنوان الهدم)', NULL, '0'),
    ('current_residence', '12.2 current place of residence', 'مكان الإقامة الحالية', NULL, '0'),
    ('current_residence_other', '12.2.1 please specify (other)', 'يرجى التحديد (أخرى)', NULL, '0'),
    ('shelter_name', '12.3 shelter name', 'اسم مركز الإيواء', NULL, '0'),
    ('shelter_type', '12.4 shelter type', 'نوع مركز الإيواء', NULL, '0'),
    ('shelter_type_other', '12.4.1 please specify (other)', 'يرجى التحديد (أخرى)', NULL, '0'),
    ('governorate', '12.5 governorate', 'المحافظة', NULL, '0'),
    ('locality', '12.6 locality', 'البلدية', NULL, '0'),
    ('neighborhood', '12.7 neighborhood', 'الحي', NULL, '0'),
    ('street', '12.8 street', 'اسم الشارع', NULL, '0'),
    ('closest_facility2', '12.9 closest facility', 'أقرب مرفق', NULL, '0'),
    ('page13', '13. household and rentee', '13. معلومات المستأجر', NULL, '0'),
    ('identity_type2', '13.1 identity type', 'نوع الوثيقة', NULL, '0'),
    ('rentee_id_passport_number', '13.2 rentee id/passport number', 'رقم هوية المستأجر/جواز السفر', NULL, '0'),
    ('rentee_resident_full_name', '13.3 rentee/resident full name', 'اسم المستأجر/المقيم', NULL, '0'),
    ('q_13_3_1_first_name', '13.3.1 first name', 'الاسم الأول', NULL, '0'),
    ('q_13_3_2_second_name__father', '13.3.2 second name (father)', 'اسم الأب', NULL, '0'),
    ('q_13_3_3_third_name__grandfather', '13.3.3 third name (grandfather)', 'اسم الجد', NULL, '0'),
    ('q_13_3_4_last_name__family', '13.3.4 last name (family)', 'اسم العائلة', NULL, '0'),
    ('rentee_mobile_number', '13.4 rentee mobile number', 'رقم جوال/هاتف المستأجر', NULL, '0'),
    ('work_type', '13.5 work type', 'طبيعة العمل', NULL, '0'),
    ('other_work', '13.5.1 if other, specify', 'في حال أخرى، حدد طبيعة العمل الآخر', NULL, '0'),
    ('page14', '14. unit finishing and internal damaged', '14. تقييم تشطيب الوحدة والأضرار الداخلية', NULL, '0'),
    ('external_finishing_of_the_unit', '14.1 external finishing of the unit', 'تشطيب الوحدة من الخارج', NULL, '0'),
    ('other_external_finishing', '14.1.1 if other, specify', 'في حال أخرى، حدد نوع التشطيب الآخر', NULL, '0'),
    ('is_finished', '14.2 is the apartment finished?', 'هل الشقة مشطبة؟', NULL, '0'),
    ('finishing_extent', '14.2.2 is the finishing total or partial?', 'هل التشطيب كلي أم جزئي؟', NULL, '0'),
    ('internal_finishing_of_the_unit', '14.2.1 internal finishing of the unit', 'تشطيب الوحدة من الداخل', NULL, '0'),
    ('finishing_partial_types', '14.2.4 partial finishing types', 'نوع التشطيب الجزئي', NULL, '0'),
    ('has_fire', '14.3 is there a fire in the housing unit?', 'هل يوجد حريق في الوحدة؟', NULL, '0'),
    ('fire_extent', '14.3.1 is the fire total or partial?', 'هل الحريق كلي أم جزئي؟', NULL, '0'),
    ('fire_severity', '14.3.2 fire severity level', 'ما هي درجة الحريق', NULL, '0'),
    ('fire_locations', '14.3.3 areas affected by fire', 'الأماكن التي تعرضت للحريق', NULL, '0'),
    ('fire_rooms_count', '14.3.4 number of rooms affected by fire', 'عدد الغرف التي تعرضت للحريق', NULL, '0'),
    ('fire_area', '14.3.5 fire affected area (m²)', 'مساحة الحريق (م²)', NULL, '0'),
    ('furniture_ownership', '14.4 who owns the furniture?', 'ملكية الأثاث تعود إلى من؟', NULL, '0'),
    ('percentage_of_damaged_furniture', '14.4.1 percentage of damaged furniture', 'نسبة تدمير الآثاث (%)', NULL, '0'),
    ('unit_stripping', '14.5 was there stripping inside the housing unit?', 'هل تم التفريغ في الوحدة السكنية؟', NULL, '0'),
    ('unit_stripping_details', '14.5.1 stripping: total or partial?', 'التفريغ: كلي أم جزئي؟', NULL, '0'),
    ('stripping_area', '14.5.2 stripping area (m²)', 'مساحة التفريغ (م²)', NULL, '0'),
    ('stripping_locations', '14.5.3 areas affected by stripping', 'حدد الأماكن التي تم التفريغ فيها', NULL, '0'),
    ('rubble_removal_is_needed', '9.3  debris removal is needed?', 'هل هناك حاجة لإزالة الركام؟', NULL, '0'),
    ('activation_of_uxo_ha_d_material_clearance', '9.4  activation of uxo/hazard material clearance?', 'هل هناك حاجة لفحص وتنظيف المواد الخطرة/المتفجرة؟', NULL, '0'),
    ('unit_support_needed', '9.6 housing unit shoring / structural support needed', 'هل تحتاج الوحدة السكنية إلى تدعيم؟', NULL, '0'),
    ('is_the_housing_unit_or_living_habitable', '9.7 is the damaged unit suitable for living (habitable)/work?', 'هل الوحدة المتضررة ملائمة للسكن/العمل؟', NULL, '0'),
    ('mhpss', '15. mental health and psychosocial support (mhpss)', 'القسم (5): الصحة النفسية والدعم النفسي الاجتماعي', NULL, '0'),
    ('mhpss_experinced', '15.1 since the war, have you or any family members experienced increased stress, anxiety, emotional challenges, and/or mental and psychological issues? if so', 'منذ بداية الحرب، هل واجهت أنت أو أي من أفراد عائلتك زيادة في التوتر، أو القلق، أو التحديات العاطفية، أو المشاكل العقلية والنفسية، أو الارق او أي مشاكل نفسية أخرى؟ إذا كان الأمر كذلك (نعم)، رجاء حدد؟', NULL, '0'),
    ('other_mhpss_exp', '15.1.1 if other, specify:', 'إذا تم اختيار آخر/أخرى في السؤال السابق، وضح الإجابة', NULL, '0'),
    ('mhpss_support', '15.2 what kind of support do you think would help you cope better (e.g., individual counseling, group therapy, family support, or community activities)?', 'ما نوع الدعم الذي تعتقد أنه سيساعدك على التكيف مع الوضع الحالي بشكل أفضل (مثل، الاستشارة الفردية، أو العلاج الجماعي، أو الدعم الأسري، أو الأنشطة المجتمعية، او غيرها)؟', NULL, '0'),
    ('other_mhpss_support', '15.2.1 if other, specify:', 'إذا تم اختيار آخر/أخرى في السؤال السابق، وضح الإجابة', NULL, '0'),
    ('community_participation', '15.3 would you be interested in participating in community-based interventions aimed at enhancing resilience and coping mechanisms?', 'هل أنت مهتم بالمشاركة في أية تدخلات مجتمعية و/أو نفسية تهدف إلى تعزيز المرونة والصمود وآليات التكيف؟', NULL, '0'),
    ('ce', '16. community needs and preferences survey', '16. استطلاع احتياجات المجتمع', NULL, '0'),
    ('ce1', '16.1 prefab housing needs', 'احتياجات المنازل الجاهزة', NULL, '0'),
    ('prefab_moving', '16.1.1 would you be interested in moving to a prefab house as a temporary solution?', 'هل ستكون مهتماً بالانتقال إلى منزل جاهز كحل مؤقت؟', NULL, '0'),
    ('prefab_moving_maybe', '16.1.2 if maybe, please specify:', 'إذا تم اختيار ربما في السؤال السابق، وضح الإجابة', NULL, '0'),
    ('prefab_types', '16.1.3 what features are most important to you in a prefab house?', 'ما هي الميزات الأكثر أهمية بالنسبة لك في المنزل الجاهز؟', NULL, '0'),
    ('other_prefab_types', '16.1.4 if other, specify:', 'إذا تم اختيار آخر/أخرى في السؤال السابق، وضح الإجابة', NULL, '0'),
    ('prefab_pref', '16.1.5 do you have any specific preferences or requirements for the prefab house? (please describe)', 'هل لديك أي تفضيلات أو متطلبات محددة للمنزل الجاهز (يرجى التوضيح) ؟', NULL, '0'),
    ('ce2', '16.2 rehabilitation needs', 'احتياجات إعادة التأهيل', NULL, '0'),
    ('reh_kitchen', '16.2.1 do you require rehabilitation of your kitchen?', 'هل يحتاج إلى إعادة تأهيل المطبخ؟', NULL, '0'),
    ('reh_bathroom', '16.2.2 do you require rehabilitation of your bathroom?', 'هل يحتاج إلى إعادة تأهيل الحمام؟', NULL, '0'),
    ('reh_type', '16.2.3 what type of rehabilitation is needed for your kitchen or bathroom? (please describe)', 'ما نوع إعادة التأهيل المطلوبة للمطبخ أو الحمام (يرجى الوصف)؟', NULL, '0'),
    ('ce3', '16.3 additional comments', 'تعليقات إضافية', NULL, '0'),
    ('additional_comments', '16.3.1 do you have any additional comments or concerns regarding temporary shelter?', 'هل لديك أي تعليقات أو مخاوف إضافية بشأن الإسكان المؤقت؟', NULL, '0'),
    ('techncial_boq', '17. techncial-boq', '', NULL, '0'),
    ('tech_boq', 'techncial-boq', '', NULL, '0'),
    ('p11', 'demolishing works', '', NULL, '0'),
    ('dm1', 'DM1-Demolish walls', 'إزالة حوائط (M2)', '120', '1'),
    ('dm2', 'DM2-Remove concrete from slabs', 'أزالة أسقف (M2)', '40', '1'),
    ('dm3', 'DM3-Remove concrete from existing damaged columns', 'إزالة أعمدة (No.)', '3', '1'),
    ('dm4', 'DM4-Carefully remove concrete from stair cases', 'إزالة درج (RM)', '3', '1'),
    ('dm5', 'DM5-Clean the site including removing debris out of site to approved damping areas.', 'تنظيف الموقع و إزالة الركام  من الموقع (M3)', '15', '1'),
    ('dm6', 'DM6-Demolish concrete ground slabs', 'إزالة مدة أرضية (M2)', '80', '1'),
    ('dm7', 'DM7-Demolish concrete beams or foundation including removing debris out of site to approved damping areas.', 'إزالة حزامات أو قواعد وإزالة ركامها من الموقع (M3)', '1', '1'),
    ('dm8', 'DM8-Carfully remove tiles', 'إزالة بلاط (M2)', '80', '1'),
    ('dm10', 'DM10-Remove marble worktop', 'إزالة المجلى كاملا ( الوجه والأرفف ... إلخ) (RM)', '5', '1'),
    ('dm11', 'DM11-Hacking and remove old plaster including removing debris out of site to approved damping areas.', 'إزالة قصارة قديمة شاملاً تنظيف الموقع (M2)', '100', '1'),
    ('dm12', 'DM12-Backfilling with clean sand', 'ردم باستخدام رمل نظيف لزوم الحفر حول المبنى (M3)', '1', '1'),
    ('p12', 'Blocks Works', '', '', '0'),
    ('bl2', 'BL2-Hollow block walling 10 - 12cm thick', 'بلوك 12 - 10 سم (M2)', '120', '3'),
    ('bl3', 'BL3-Hollow block walling 15cm thick', 'بلوك 15 سم (M2)', ' 120', '3'),
    ('bl4', 'BL4-Hollow block walling 20cm thick', 'بلوك 20 سم (M2)', ' 120', '3'),
    ('bl5', 'BL5-Solid block walling 20cm thick', 'بلوك بلدي 20 سم (M2)', ' 120', '3'),
    ('p13', 'Concrete Works', '', '', '0'),
    ('co2', 'CO2-Supply and cast reinforced concrete (B250/20) for ground slab with [10cm] thick,', 'توريد وصب خرسانة مسلحة بقوة (B250/20) لأعمال مدة أرضية بسماكة 10سم (M2)', '80', '1'),
    ('co3', 'CO3-Supply and cast reinforced concrete (B250/20) in door jambs, canopies, secondary tie columns,secondary beams, lintel, sills, infil and topping to walls', 'توريد وصب خرسانة مسلحة بقوة (B250/20) لأعمال الجلسات والكشفات  (M3)', '1.5', '1'),
    ('co4', 'CO4-Supply and cast reinforced concrete (B250/20) for ground beams or foundation', 'توريد وصب خرسانة مسلحة بقوة (B250/20) لأعمال الأحزمة الأرضية والقواعد (M3)', '1', '1'),
    ('co5', 'CO5-Supply and cast reinforced concrete (B300/20) for new columns', 'توريد وصب خرسانة مسلحة بقوة (B300/20) لأعمال الأعمدة الجديدة (M3)', '1', '1'),
    ('co6', 'CO6-Supply and cast reinforced concrete (B300/20) as protective sleeve cover around existing damaged columns.', 'توريد وصب خرسانة مسلحة بقوة (B300/20) لأعمال غطاء خرساني (قمصان) حول الأعمدة المتضررة (No)', '1', '1'),
    ('co7', 'CO7-Supply and cast reinforced concrete (B250/...)', 'توريد وصب خرسانة مسلحة بقوة (B250/20) لأعمال السقف المصمت بسماكة 15 - 10سم  (M2)', '40', '4'),
    ('co8', 'CO8-Supply and cast reinforced concrete (B250/20) for suspended hollow block slab [25cm average thick]', 'توريد وصب خرسانة مسلحة بقوة (B250/20) لأعمال الأسقف باستخدام بلوك مفرغ (ريبس) بسماكة  متوسط 25  سم  (M2)', '40', '4'),
    ('co9', 'CO9-Supply & cast reinforced concrete (B250/20) for stair case (landing, flights, steps & beams)', 'توريد وصب خرسانة مسلحة بقوة (B250/20) لأعمال الدرج (الشواحط والدرجات والأحزمة) (M3)', '1', '2'),
    ('co10', 'CO10-Provide wooden shuttering and steel support for existing roof slab or any structural element as directed by supervising engineer.', 'تدعيم بدعائم خشبية ومعدنية لسقف أو أي عنصر إنشائي يحتاج لتدعيم (M2)', '40', '1'),
    ('p14_1', 'Internal Finishings Works', 'أعمال التشطيبات الداخلية', '', '0'),
    ('p14_1_1', 'Painting Works', 'أعمال الدهان', '', '0'),
    ('fn1', 'FN1-Priming and painting with at least two coats of high quality acrylic emulsion paint (Supercryle) for walls and ceiling surfaces.', 'تأسيس ودهان على الأقل طبقتين (سوبركريل) للحوائط والاسقف (M2)', '300', '5'),
    ('fn2', 'FN2-Priming and painting with at least two coats of high quality oil paint for walls.', 'تأسيس ودهان على الأقل طبقتين (دهان زيت) للحوائط (M2)', '300', '5'),
    ('p14_1_2', 'Tiling Works', 'أعمال البلاط', '', '0'),
    ('fn5', 'FN4-Supply and install terrazzo with marble chips floor tiles and skirting (7cm high)', 'توريد وتركيب بلاط كسر رخام شاملاً بلاط البانيل بسمك 7 سم (M2)', '80', '6'),
    ('fn6', 'FN6-Supply and install glazed ceramic wall tiles', 'توريد وتركيب بلاط حوائط سراميك (M2)', '80', '1'),
    ('fn7', 'FN7-Supply and install ceramic floor tiles', 'توريد وتركيب بلاط أرضي سراميك  (M2)', '80', '6'),
    ('fn8', 'FN8-Supply and install Porcelain or multi-purpose marble (M2.)', 'توريد وتركيب  بلاط بورسولان أو خشب بركيه (M2)', '80', '6'),
    ('fn10', 'FN10-Supply and installation of granolithic finish for floors or walls', 'توريد وتركيب جرانيوليت للأرضيات أو الحوائط (M2)', '1', '1'),
    ('p14_1_3', 'Marble Works', 'أعمال الرخام', '', '0'),
    ('fn11', 'FN8-Supply and install marble sills (RM.)', 'تويد وتركيب جلسات رخام خليلي أو كسر رخام بعرض 25 سم (RM)', '10', '1'),
    ('fn12', 'FN12-Marble worktop  ( Complete including top, shelves, walls, … etc)', 'توريد وتركيب رخام مجلى (كامل يشمل الوجه والرفوف ... إلخ) (RM)', '5', '7'),
    ('fn13', 'FN13-Supply and fix Granite marble only', 'توريد وتركيب وجه جرانيت (M2)', '3', '1'),
    ('fn14', 'FN14-Maintenance of Kitchen marble', 'صيانة رخام مطبخ (RM)', '5', '7'),
    ('fn15', 'FN15- Supply and install multi-purpose marble (M2.)', 'توريد و تركيب رخام متعدد الإستخدامات (M2)', '2', '1'),
    ('fn4', 'FN9-Supply and install precast terrazzo for stair case or Marble', 'توريد وتركيب درج (كسر رخام) أو رخام  (RM)', '10', '2'),
    ('p14_1_4', 'Plastering Works (Gypsum / Plaster)', 'أعمال القصارة (لياسة / جبس)', '', '0'),
    ('fn22', 'FN22-Supply & fix gypsum decorated panel (wide) include material & workmanship', 'توريد وتركيب جبس للديكور الداخلي (عريض) شاملاً المواد والعمالة (RM)', '60', '8'),
    ('fn23', 'FN23-Supply & fix gypsum decorated panel (Thin) include material & workmanship', 'توريد وتركيب جبس للديكور الداخلي (كرانيش) شاملاً المواد والعمالة (RM)', ' 60', '8'),
    ('fn24', 'FN24-Supply & fix gypsum decorated panel  include material & workmanship', 'توريد وتركيب جبس (ألواح) للديكور الداخلي شاملاً المواد والعمالة (M2)', ' 60', '1'),
    ('fn25', 'FN25-Supply and install gypsum board walls, including all materials and workmanship', 'توريد وتركيب حوائط جبس بورد، شاملاً المواد والعمالة (M2)', '20', '1'),
    ('fn26', 'FN26-Supply and installation of false ceiling (gypsum board), including all materials and workmanship.', 'توريد وتركيب سقف مستعار  شاملاً المواد والعمالة (M2)', '60', '1'),
    ('fn16', 'FN16-Internal plastering, 13mm thick to walls and ceilings.', 'قصارة داخلية بسماكة 13 مم للحوائط والسقف (M2)', '100', '1'),
    ('fn17', 'FN17-External rendering, 15mm thick with approved dampproof admixture to walls.', 'قصارة خارجية بسماكة 15 مم (M2)', '100', '9'),
    ('fn18', 'FN18-Ditto but lime free external rendering.', 'قصارة خارجية بدون استخدام الشيد (M2)', '100', '9'),
    ('fn19', 'FN19-External tyrolean finish with white cement ad fine sand (kfars) mix (1:3) to walls.', 'رشقة خارجية باستخدام رمل ناعم و أسمنت أبيض بنسبة (1/3) (M2)', '80', '10'),
    ('fn21', 'FN21-Plastering, rendering and repairing cracks', 'قصارة ومعالجة وإصلاح الشقوق (RM)', '50', '1'),
    ('p14_2', 'External Finishings Works', 'أعمال التشطيبات الخارجية', '', '0'),
    ('fn27', 'FN27-Supply and install exterior natural stone.', 'توريد وتركيب حجر قدسي (M2)', '80', '10'),
    ('fn28', 'FN8-Supply and install Porcelain or multi-purpose marble (M2.)', 'توريك وتركيب كرميد شاملا كل ما يحتاجه من مواد وأعمال (M2)', '80', '1'),
    ('fn29', 'FN29-Supply and installation of interlock tiles, 6 cm thick', 'توريد وتركيب بلاط إنترلوك سماكة 6 سم', '20', '1'),
    ('fn30', 'FN30-Supply and install interlocking paving tiles, 8 cm thickness', 'توريد وتركيب بلاط إنترلوك سماكة8 سم', '3', '1'),
    ('fn31', 'FN31-External Italian Plaster finish.', 'شلختة إيطالية (M2)', '80', '10'),
    ('p15', 'Aluminum Works', '', '', '0'),
    ('al1', 'AL1-Supply and fix complete aluminum window of 4-6mm thick waved glazed sliding leaves', 'توريد وتركيب نوافذ ألمنيوم كاملة بسماكة 4-6 مم (سحاب - منزلقة) (M2)', ' 15', '11'),
    ('al2', 'AL2-Supply and fix complete aluminum window of 4-6mm thick waved glazed moving leaves', 'توريد وتركيب نوافذ ألمنيوم كاملة بسماكة 4-6 مم (قلاب - متحركة) (M2)', ' 15', '11'),
    ('al3', 'AL3-Supply and fix complete aluminum window of 4-6mm thick waved glazed fixed leaves', 'توريد وتركيب نوافذ ألمنيوم كاملة بسماكة 4-6 مم (ثابتة) (M2)', ' 15', '11'),
    ('al4', 'AL4-Supply and fix aluminum window of plastic panel louvered sliding leaves.', 'توريد وتركيب نوافذ ألومنيوم (لوفر) بلاستيك ( سحاب - منزلقة) (M2)', '15', '11'),
    ('al5', 'AL5-Supply and fix aluminum window of plastic panel louvered moving leaves.', 'توريد وتركيب نوافذ ألومنيوم  (لوفر) بلاستيك (قلاب -متحركة) (M2)', '15', '11'),
    ('al6', 'AL6-Supply and fix aluminum window of plastic panel louvered fixed leaves.', 'توريد وتركيب نوافذ ألومنيوم  (لوفر) بلاستيك (ثابتة) (M2)', '15', '11'),
    ('al7', 'AL7-Supply and install leaves for aluminum window or door to match the existing', 'توريد وتركيب ضلفات لشبابيك الالمنيوم (M2)', '15', '11'),
    ('al8', 'AL8-Supply and install  aluminum frame', 'توريد وتركيب حلق ألمنيوم (RM)', '13', '1'),
    ('al9', 'AL9-Maintenance of aluminum window or door ( Excluding glass).', 'صيانة شبابيك أو أبواب ألمنيوم بدون زجاج (M2)', '15', '1'),
    ('al10', 'AL10-Supply and install curtain wall system', 'توريد وتركيب كيرتن وول (متر مربع) (M2)', '1', '1'),
    ('al11', 'AL-11 Supply and install Aluminum Door (NO)', 'توريد وتركيب أبواب ألمنيوم (No)', '3', '1'),
    ('p16', 'Wood Works', '', '', '0'),
    ('wd1', 'WD1-Supply and install wooden door Type D1, V-jointed, size (90-80x220x4.5)cm', 'توريد وتركيب أبواب خشبية يشمل الحلق، حجم (80-90 *220*4.5) سم (No.)', ' 7', '12'),
    ('wd3', 'WD3-Maintenance of wooden window or door include frame', 'صيانة أبواب أو نوافذ خشبية شامل الحلق (No.)', '7', '12'),
    ('wd4', 'WD4-Supply and fix wooden window.', 'توريد وتركيب نوافذ خشبية (No.)', '', '0'),
    ('wd5', 'WD5-Supply and install timber leaves for wooden window or door.', 'توريد وتركيب ضلفة باب أو نافذة خشبية (No.)', ' 7', '12'),
    ('wd6', 'WD6 -Supply and install wooden door frame15 cm (No.)', 'توريد وتركيب حلق باب خشب15  سم (No.)', ' 7', '13'),
    ('wd7', 'WD7–Supply and install wooden door frame, 18 cm (No.)', 'توريد وتركيب حلق باب خشب 18سم (No.)', ' 7', '13'),
    ('wd8', 'WD8-Supply and install wooden door frame, 23 cm (No.)', '   توريد وتركيب حلق باب خشب 23سم (No.)',  '7', '13'),
    ('wd9', 'WD9-Supply and install wooden staircase (Mr.)', 'توريد وتركيب  درج خشبي (Mr.)', '3', '1'),
    ('wd10', 'WD10-Supply and install wooden mezzanine (M2.)', 'توريد وتركيب سدة خشبية (M2.)', '40', '1'),
    ('wd12', 'CM12-Supply and install hardware with switch or door hands.', 'توريد وتركيب زرفيل  أو يدين باب (No.)', '7', '1'),
    ('p17', 'Metal Works', '', '', '0'),
    ('mt1', 'MT1-Supply and install galvanized steel sheets (type skourit) 0.5mm thick .', 'توريد وتركيب ألواح زينجو (سكوريت) بسماكة 0.5 مم (M2)', '80', '1'),
    ('mt2', 'MT2-Supply and install eternite sheets fixed to steel pipes or purlins.', 'توريد وتركيب ألواح اسبست (M2)', '80', '1'),
    ('mt3', 'MT3-Dismantle and refix steel pipes and eternite sheets or skourit .', 'إعادة تركيب وإصلاح مواسير أو ألواح زينجو (سكوريت) أو اسبست (M2)', '80', '1'),
    ('mt4', 'MT4-Supply and install 4\'\' mild steel pipes.', 'توريد وتركيب مواسير حديد قطر 4 إنش (RM)', '70', '1'),
    ('mt5', 'MT5-Supply and install open steel profile 80x40 mm.', 'توريد وتركيب بروفيل معدني 8*4 سم (RM)', '70', '1'),
    ('mt6', 'MT6-Supply and install steel door size [120x220]cm.', 'توريد وتركيب أبواب حديد (120*220) سم (No.)', '2', '15'),
    ('mt7', 'MT7-Maintenance of steel door size [120x220]cm.', 'صيانة أبواب معدنية (120*220) سم (No.)', '2', '15'),
    ('mt8', 'MT8-Supply and install steel door', 'توريد وتركيب أبواب معدنية (أبواب حواصل) (No)', '2', '1'),
    ('mt9', 'MT9-Maintenance of steel door', 'صيانة أبواب معدنية (أبواب حواصل)  (No.)', '2', '1'),
    ('mt10', 'MT10-Supply and fix steel balustrade for stair case.', 'توريد وتركيب دربزين معدني للدرج (RM)', '3', '1'),
    ('mt11', 'MT11-Supply and fix steel security protective screen.', 'توريد وتركيب حديد حماية للنوافذ (M2)', '8', '1'),
    ('mt13', 'MT13-New Mul-T-lock Door with frame', 'باب ملتيلوك جديد مع حلق للباب (No.)', '2', '16'),
    ('mt14', 'MT14-New Mul-T-lock Door without frame', 'باب ملتيلوك جديد بدون حلق للباب (No.)', '2', '16'),
    ('mt15', 'MT15-PVC coating', 'جلد باب ملتي لوك (No.)', '2', '16'),
    ('mt16', 'MT16-New door lock', 'قفل باب جديد (No.)', '2', '16'),
    ('mt17', 'MT17-Complete maintenace for Mul-T-lock Door', 'صيانة كاملة لباب ملتيلوك (No.)', '2', '16'),
    ('mt19', 'MT19-Supply and install steel emergency escape staircase (linear meter)', 'توريد وتركيب درج هروب حديدي (متر طولي)', '1', '1'),
    ('p18', 'Combined', '', '', '0'),
    ('cm1', 'CM1-Replacement of broken glass 4mm thick for any defected parts.', 'إستبدال زجاج مكسور بسمك 4 مم (M2)', '15', '14'),
    ('cm2', 'CM2-Replacement of broken glass 6mm thick for any defected parts.', 'إستبدال زجاج مكسور بسمك 6 مم (M2)', ' 15', '14'),
    ('cm3', 'CM3-Replacement of broken glass colored 4mm thick (Reflector) for any defected parts.', 'إستبدال زجاج مكسور بسمك 4 مم عاكس (M2)', ' 15', '14'),
    ('cm4', 'CM4-Replacement of broken glass colored 6mm thick (Reflector) for any defected parts.', 'إستبدال زجاج مكسور بسمك 6 مم عاكس (M2)', '15', '14'),
    ('cm5', 'CM5-Replacement of broken (reinforced) glass 6mm thick  for any defected parts.', 'إستبدال زجاج بشبك معدني (مسلح) بسمك 6 مم (M2)', '15', '14'),
    ('cm6', 'CM6-Replacement of broken panels for louver leaves with all needed accessories', 'إستبدال زجاج لوفر مكسور (M2)', ' 15', '14'),
    ('cm7', 'CM7-Supply and install fly screen for leaves with all needed acessories.', 'توريد وتركيب شبك للنوافذ (M2)', '7', '1'),
    ('cm8', 'CM8-Supply and install securit glass', 'توريد وتركيب زجاج سيكوريت (M2)', '10', '1'),
    ('cm9', 'CM9-Supply and installation of lower kitchen cabinets (aluminum).', 'توريد وتركيب خزائن مطبخ سفلي (ألمنيوم ) (RM)', '7', '1'),
    ('cm12', 'CM10-Supply and installation of kitchen cabinets (aluminum ).', 'توريد وتركيب خزائن مطبخ علوي (ألمنيوم ) (RM)', '7', '1'),
    ('cm13', 'CM11-Maintenance kitchen cabinets (aluminum ).', 'صيانة خزائن مطبخ (ألمنيوم ) (RM)', '7', '1'),
    ('cm14', 'CM9-Supply and installation of lower kitchen cabinets (Wood).', 'توريد وتركيب خزائن مطبخ سفلي (خشب ) (RM)', '7', '1'),
    ('cm15', 'CM10-Supply and installation of kitchen cabinets (Wood ).', 'توريد وتركيب خزائن مطبخ علوي (خشب ) (RM)', '7', '1'),
    ('cm16', 'CM11-Maintenance kitchen cabinets (Wood ).', 'صيانة خزائن مطبخ (خشب ) (RM)', '7', '1'),
    ('cm10', 'CM12-Supply and installation of PVC cladding pergola', 'توريد وتركيب معرش جلد (M2) (PVC)', '6', '1'),
    ('p19', 'Plumping Works', '', '', '0'),
    ('pm1', 'PM1-Complete solar heating system', 'حمام شمسي كامل يشمل السيبة المعدينة (Item)', '1', '2'),
    ('pm2', 'PM2-Solar heater cylinder 150 liter.', 'سخان شمسي بسعة 150 لتر فأكثر (Item)', '1', '2'),
    ('pm101', 'PM101-Supply and install solar heating system steel stand, average size of 100x100x200cm mild steel', 'توريد وتركيب سيبة حمام شمسي 200 * 100* 100 سم (No.)', '2', '2'),
    ('pm18', 'PM18-Complete single mirror size 190x90cm for solar system best quality.', 'مرآة حمام شمسي  190*90 سم (No.)', '3', '2'),
    ('pm19', 'PM19-2mm clear glass sheet for solar system mirrors best quality,', 'زجاج مرآة حمام شمسي (M2)', '6', '1'),
    ('pm3', 'PM3-0.5M3 capacity plastic water tank.', 'خزان مياه بسعة 500 لتر (Item)', '2', '17'),
    ('pm4', 'PM4-1.0M3 capacity plastic water tank', 'خزان مياه بسعة 1000 لتر (Item)', '2', '17'),
    ('pm5', 'PM5-1.5M3 capacity plastic water tank', 'خزان مياه بسعة 1500 لتر (Item)', '2', '17'),
    ('pm6', 'PM6-2.0M3 capacity plastic water tank', 'خزان مياه بسعة 2000 لتر (Item)', '2', '17'),
    ('pm7', 'PM7-Maintenance of Water tank', 'صيانة خزان مياه (No.)', '2', '1'),
    ('pm8', 'PM8-Maintenance of Water network', 'صيانة شبكة مياه  (No.)', '1', '2'),
    ('pm9', 'PM9-Dismantle and refix solar heating system.', 'فك وإعادة تركيب سخان شمسي كاملاً (Item)', '1', '2'),
    ('pm10', 'PM10-UPVC drainage pipes 4" internal diameter', 'أنابيب (مواسير) UPVC قطر 4 إنش (MR)', '8', '2'),
    ('pm11', 'PM11-UPVC drainage pipes 6" internal diameter.', 'أنابيب (مواسير) UPVC قطر 6 إنش (MR)', '5', '2'),
    ('pm12', 'PM12-UPVC drainage pipes 2" or 3" .', 'أنابيب (مواسير) UPVC قطر 2 أو 3 إنش (MR)', '8', '2'),
    ('pm13', 'PM13-Galavanized steel pipes [3/4"]', 'أنابيب (مواسير) معدنية مجلفنة قطر 3/4 انش (MR)', '3', '2'),
    ('pm14', 'PM14-20mm PVC water pipes [Gulanee] with sleeves 25 mm', 'أنابيب (مواسير) جولاني 20مم شاملاً أنابيب (مواسير) شرشوري قطر 25 مم (MR)', '25', '1'),
    ('pm40', 'PM40-Rehabilitate Water Distribution Box (W.D.B.)', 'إعادة تأهيل طبلون المياة (NO)', '1', '2'),
    ('pm15', 'PM15-1/2"Galavanized steel pipes with all fittings including priming & painting.', 'أنابيب 1/2" (مواسير) حديد مجلفن شاملاً الوصلات والتأسيس والدهان (MR)', '3', '2'),
    ('pm16', 'PM16-Trapped floor gully 4" diameter', 'مصفاة أرضية 4 إنش (No.)', '3', '1'),
    ('pm20', 'PM20-Flushing cistern box', 'صندوق طرد/تصريف مياه (نيجارة) (No.)', '2', '1'),
    ('pm21', 'PM21-0.5" Tibisa type chromium water mixer', 'خلاط مياه 0.5 إنش (No.)', '5', '2'),
    ('pm22', 'PM22-0.5" Tibisa type chromium water tap', 'صنبور مياه 0.5 إنش (No.)', '2', '2'),
    ('pm23', 'PM23-White glazed hand wash basin size 52x40cm', 'مغلسة حمام (No.)', '3', '2'),
    ('pm24', 'PM24-Shower Tray 700 X700mm (Ariston type or equivelent).', 'حوض إستحمام (أريستون) (No.)', '1', '2'),
    ('pm25', 'PM25-White glazed fireclay sink size 610x405mm', 'حوض ستانليس للمجلى (No.)', '1', '2'),
    ('pm26', 'PM26-White glazed fireclay squatting W.C [European/Arabic]', 'كرسي حمام (افرنجي أو عربي) (No.)', '2', '2'),
    ('pm27', 'PM27-One layer bituminous membrane with chippings 4mm thick of high ductility (polybeed)', 'عزل بطبقة بولوبيد بسمك 4 مم (M2)', '80', '1'),
    ('pm28', 'PM28-Manhole 40cm internal diameter', 'منهل قطر 40 سم (No.)', '1', '2'),
    ('pm29', 'PM29-Manhole 50cm internal diameter', 'منهل قطر 50 سم (No.)', '1', '2'),
    ('pm30', 'PM30-Water pump 0.5 HP including all acessories', 'مضخة مياه نص حصان مع كافة لوازمها (Item)', '1', '18'),
    ('pm31', 'PM31-Water pump 3/4 HP including all acessories', 'مضخة مياه 3/4 حصان مع كافة لوازمها (Item)', '1', '18'),
    ('pm32', 'PM32-Ditto but 1.0 HP', 'مضخة مياه 1حصان مع كافة لوازمها (Item)', '1', '18'),
    ('pm33', 'PM33-Septic tank size 165X90X140cm', 'بئر مياه صرف صحي  (Item)', '1', '1'),
    ('pm34', 'PM34-Percolation Pit size 240cm internal dimeter and 400cm high', 'حفرة ترشيح إمتصاصية (Item)', '1', '2'),
    ('pm35', 'PM35-Submersible water well', 'بئر مياه غاطس (Item)', '1', '2'),
    ('pm36', 'PM36-Underground water tank (capacity 5 m3)', 'خزان مياه أرضي سعة 5 م3 (Item)', '1', '2'),
    ('pm37', 'PM37-Water lifting pump (capacity in HP)', 'ماتور رفع مياه (القدرة بالحصان 3 حصان فأكثر) (Item)', '1', '2'),
    ('pm38', 'PM38-Manhole 60cm internal diameter', 'منهل صرف صحي قطر 60 سم (No.)', '1', '2'),
    ('pm39', 'PM39-Manhole 80cm internal diameter', 'منهل صرف صحي قطر 80 سم (No.)', '1', '2'),
    ('p20', 'Electrical Works', '', '', '0'),
    ('el1', 'EL1-Three pins 16A socket outlet', 'إبريز 16 أمبير (No.)', ' 15', '19'),
    ('el2', 'EL2-Three pins 16A socket outlet(waterproove)', 'إبريز 16 أمبير ضد المياه (No.)', ' 15', '19'),
    ('el3', 'EL3-Three pins 16A socket outlet  with 3X2.5mm2 wire and conduits from SBD to the points.', 'إبريز 16 أمبير شاملاً سلك 2.5 مم2 وتوصيله إلى علبة التجميع (No.)', '15', '19'),
    ('el4', 'EL4-One gang one way switch (waterproove)', 'مفتاح مفرد ضد المياه (No.)', '4', '1'),
    ('el5', 'EL5-One gang one way switch', 'مفتاح مفرد  (No.)', '6', '20'),
    ('el6', 'EL6-One gang one way switch  with 1.5mm2 wire and conduits from SDB to the point.', 'مفتاح مفرد شاملاً سلك التوصيل 1.5مم2 إلى علبة التجميع (No.)', '6', '20'),
    ('el7', 'EL7-Two gang one way switch  inculding all connections.', 'مفتاح مزوج  بدون سلك (No.)', '6', '21'),
    ('el8', 'EL8-Tow gang one way switch with 1.5mm2 wire and conduits from SDB to the point.', 'مفتاح مزوج مع سلك 1.5 مم2 والتوصيل إلى علبة التجميع (No.)', '6', '21'),
    ('el9', 'EL9-Flourescent lighting fixture 1x40w with lamp and 3X1.5mm2  wire and conduit', 'نيون مفرد كامل شاملا توصيلاته واللمبة  (No.)', '10', '23'),
    ('el24', 'EL24-Flourescent lighting fixture 2x40w with lamp and 3X1.5mm2  wire and conduit', 'نيون مزدوج كامل شاملا توصيلاته واللمبة  (No.)', '10', '23'),
    ('el10', 'EL10-Circular glob 60w with 3X1.5mm2 wire and conduits', 'كلوب 60 وات مع السلك وما يلزم (No.)', '5', '1'),
    ('el11', 'EL11-Ceiling lighting point with 60watt tungesten lamp and wires, conduits', 'دواية 60 وات مع لمبة وتوصيلاتها (No.)', '4', '1'),
    ('el25', 'EL25-Circular water proof glob 60w with 3X1.5mm2 wire and conduits', 'دواية 60 وات مع لمبة وتوصيلاتها ضد المياه (No.)', '3', '1'),
    ('el27', 'EL27-Supply and installation of lighting spotlights', 'توريد وتركيب سبوتات إنارة (No.)', '60', '1'),
    ('el26', 'EL26-Supply and Installation of Ceiling Fan', 'توريد وتركيب مروحة سقف (No.)', '5', '1'),
    ('el12', 'EL12-Supply and install 2X10 mm2XLPE cable with stay wire from MDB to the main electrical network including isolator porcelain cup', 'توريد وتركيب كابل 2*10 مم2 من عمود الكهرباء إلى علبة تجميع الكهرباء المنزلية (RM)', '23', '1'),
    ('el13', 'EL13-Supply and install 2" Galvanized steel console 3meter long', 'كنزولة قطر 2" وطول 3متر من الحديد المجلفن (Item)', '1', '2'),
    ('el14', 'EL14-Supply and install 1-phase KWHM , ABB type with 1X40 A circuit breaker  inside 30X40cm CI box.', 'عداد كهرباء (No.)', '1', '2'),
    ('el15', 'EL15-PVC SDB, 24 way type is Siemens or equal approved comprising:- One 1x40A C.B - One 2x40A/0.03 ELCB - Four 1x10A C.B - Six 1x16 A C.B - Earth & nutral bus bars.', 'علبة كهرباء كاملة شاملة أمانات (1*40 أمبير،4*10 أمبير، 6*16 أمبير،وتوصيلات الإيرث وتوصيلات العلبة) (Item)', '1', '2'),
    ('el16', 'EL16-Rearrange the existing wires using PVC pipe and repair all defects or fault in the internal network', 'إعادة ترتيب وصيانة شبكة الكهرباء الداخلية (Item)', '1', '2'),
    ('el17', 'EL17-Supply and install PVC cover for electrical point (circular or rectangular junction boxes)', 'غطاء علبة تجميع الكهرباء (طبلون) (No.)', '1', '2'),
    ('el18', 'EL18-Relocate KWHM to the new location with all necessary needed, cable, conduit and connection.', 'تغيير مكان علبة تجميع الكهرباء (Item)', '1', '2'),
    ('el19', 'EL19-Earthing system consists of 150cm CU electrode with 6mm2 stranded wire from SDB to the electrode with concrete manhole 40cm internal diameter and cover Râ‰¤5 ohms', 'نظام الإيرث شاملاً إليكترود 150 سم مع توصيلاته إلى علبة تجميع الكهرباء (Item)', '1', '2'),
    ('el20', 'EL20-Circuit breaker 1x10A', 'قاطع كهربائي  1*10 أمبير (No)', '15', '22'),
    ('el21', 'EL21-Circuit breaker 1x16A', 'قاطع كهربائي  1*16 أمبير (No)', '15', '22'),
    ('el22', 'EL22-Circuit breaker 1x20A', 'قاطع كهربائي  1*20 أمبير (No)', '15', '22'),
    ('el23', 'EL23-2x40A/0.03 ELCB', 'أمان الحياة 2/40 أمبير (No)', '1', '2'),
    ('el28', 'EL28-Main Distribution Board (MDB) - main electrical panel (amperage connection)', 'طبلون كهرباء رئيسي (لوحة توزيع رئيسية) (الاشتراك بالأمبير) (32،40،63،80،100،160)', '', ''),
    ('el29', 'EL29-CCTV system (surveillance cameras)', 'نظام مراقبة (كاميرات) (Item)', '1', '2'),
    ('el30', 'el30-generator (capacity in kw) (total damage / maintenance)', 'مولد (القدرة بالكيلو وات) (ضرر كلي / صيانة) (item)', NULL, '0'),
    ('p21', 'pv system works', '', NULL, '0'),
    ('pv_note', 'منظومة الخلايا الشمسية', 'قدرة المنظومة بالكامل بالوط', NULL, '0'),
    ('pv1', 'pv1- total solar system capacity (w)', 'القدرة الإجمالية للنظام الشمسي (واط)', NULL, '0'),
    ('pv2', 'pv2- inverter (1k)', 'عدد الانفيرتر1 كيلو', NULL, '0'),
    ('pv3', 'pv2- inverter (2k)', 'عدد الانفيرتر2 كيلو', NULL, '0'),
    ('pv4', 'pv2- inverter (3k)', 'عدد الانفيرتر3 كيلو', NULL, '0'),
    ('pv5', 'pv3- inverter (5k)', 'عدد الانفيرتر 5 كيلو', NULL, '0'),
    ('pv6', 'pv4- inverter (> 5k)', 'عدد الانفيرتر أكبر من 7 كيلو', NULL, '0'),
    ('pv7', 'batteries 100', 'عدد البطاريات 100 أميبر', NULL, '0'),
    ('pv8', 'batteries 200', 'عدد البطاريات 200 أميبر', NULL, '0'),
    ('pv9', 'batteries 2v', 'عدد البطاريات 2 فولت', NULL, '0'),
    ('pv10', 'batteries 3k', 'عدد البطاريات الليثوم 3 كيلو', NULL, '0'),
    ('pv11', 'batteries 5k', 'عدد البطاريات الليثوم 5 كيلو', NULL, '0'),
    ('pv12', 'pv5- distribution board', 'طبلون المنطومة', NULL, '0'),
    ('p22', 'miscellaneous works', '', NULL, '0'),
    ('item1', 'item 1', 'وصف البند مع إضافة الوحدة', NULL, '0'),
    ('quant1', 'quantity', 'الكمية', NULL, '0'),
    ('item2', 'item 2', 'وصف البند مع إضافة الوحدة', NULL, '0'),
    ('quant2', 'quantity', 'الكمية', NULL, '0'),
    ('item3', 'item 3', 'وصف البند مع إضافة الوحدة', NULL, '0'),
    ('quant3', 'quantity', 'الكمية', NULL, '0'),
    ('item4', 'item 4', 'وصف البند مع إضافة الوحدة', NULL, '0'),
    ('quant4', 'quantity', 'الكمية', NULL, '0'),
    ('item5', 'item 5', 'وصف البند مع إضافة الوحدة', NULL, '0'),
    ('quant5', 'quantity', 'الكمية', NULL, '0'),
    ('photos_final_comments_unilt', 'photos & final comments', '', NULL, '0'),
    ('damge_photo_1', 'take a photo for the damaged unit', 'خذ صورة للوحدة المتضررة', NULL, '0'),
    ('final_comments', 'Final Comments and Recommendations', 'الملاحظات والتوصيات النهائية من قبل الماسح', NULL, '0');
