UPDATE users u
JOIN (
    SELECT 'Mohammed.Alhaj' AS assignedto, 'Mohammed  Al Hajj' AS match_name
    UNION ALL SELECT 'Tariq.Alsallout', 'Tareq E. K. Alsallout'
    UNION ALL SELECT 'Mohemmed.Isleem', 'Mohemmed Saleem Hammouda isleem'
    UNION ALL SELECT 'Omar.Abumoor', 'Omar K. H. Abumor'
    UNION ALL SELECT 'Ismail.Alshakh.Ahmed', 'Ismail H. I. Alshakh Ahmed'
    UNION ALL SELECT 'Yousef.Abuibaid', 'Youssef M. Y. Abu Obeid'
    UNION ALL SELECT 'Kholood.Othman', 'Kholood S. A. Othman'
    UNION ALL SELECT 'Zhraa.Derraji', 'Zahraa A. K . Daraji'
    UNION ALL SELECT 'Ibrahim.Alqedra', 'Ibrahim shawqi alqedra'
    UNION ALL SELECT 'Merwad.Almassri', 'Merwad M. S. Al- massri'
    UNION ALL SELECT 'Sara.Abumostafa', 'Sara A. A. Abumustfa'
    UNION ALL SELECT 'Madleen.AlQeeq', 'Madleen A. S. Al Geeg'
    UNION ALL SELECT 'Doha.Bream', 'Doha Z. A. Al-Brim'
    UNION ALL SELECT 'Khaled.Alyazji', 'Khalid A.K Alyazjaa'
    UNION ALL SELECT 'Osama.Alazeez', 'Osama Hossam Mustafa Abdel Aziz'
    UNION ALL SELECT 'Mohammed.Hammad', 'Mohammed Hassan Mohammed Hammad'
    UNION ALL SELECT 'Moamen.Alashqar', 'Momen H. M. Al-Ashqar'
    UNION ALL SELECT 'Ramzi.Hamad', 'Ramzi N. M. Hamad'
    UNION ALL SELECT 'Raghad.Abumuailq', 'Raghad G. A. Abu Muailiq'
    UNION ALL SELECT 'Mohammed.Haloub', 'Mohammed Abu Haloub'
    UNION ALL SELECT 'Mohamed.Ghaith', 'Mohamed Mahmoud Ahmed Ghaith'
    UNION ALL SELECT 'Heba.Temraz', 'Hiba A. M. Tamraz'
    UNION ALL SELECT 'Hessin.Naeim', 'Hesssin J. E. Naeim'
    UNION ALL SELECT 'Amjed.Nada', 'Amjed M. I. Nada'
    UNION ALL SELECT 'Osama.Alharazeen', 'Osama A. S. Al- Harazeen'
    UNION ALL SELECT 'Hatim.Matar', 'Hatem Mohammed Hamdan Mattar'
    UNION ALL SELECT 'Ghada.Habash', 'Ghada M. A. Al-Habash'
    UNION ALL SELECT 'Abeer.Saleh', 'Abeer A. M. Saleh'
    UNION ALL SELECT 'Ahmed.Asqool', 'Ahmed Omar Abbas Asqool'
    UNION ALL SELECT 'Mahmmoud.Rajab', 'Mahmmoud R. A. Rajab'
    UNION ALL SELECT 'Oday.Elhalimy', 'ODAY M. T. ELHALIMY'
    UNION ALL SELECT 'Yousef.Hamooda', 'Yousef A. M. Hamooda'
    UNION ALL SELECT 'Marah.Dwaima', 'Marah Sameer Kamel Dwaima'
    UNION ALL SELECT 'Amal.Busafia', 'AMAL S . A BUSAFIA'
    UNION ALL SELECT 'Mohammed.Lolo', 'Mohammed Z. M. Lolo'
    UNION ALL SELECT 'Dina.Alkhatib', 'DINA H. A. ALKHATIB'
    UNION ALL SELECT 'Aya.Shublaq', 'Aya A. M. Shublaq'
    UNION ALL SELECT 'Thekrayat.Saadat', 'THEKRAYAT A. A. SAADAT'
    UNION ALL SELECT 'Fawzy.Ghannam', 'Fawzy  F. F. Ghannam'
    UNION ALL SELECT 'Nour.Issa', 'NOUR I. O. ISSA ( ALBHAISI)'
    UNION ALL SELECT 'Heba.Alkhalili', 'HEBA B. R. ALKHALILI'
    UNION ALL SELECT 'Abdallah.Alnajaar', 'Abdallah M.K Alnajaar'
    UNION ALL SELECT 'Mohammed.Alsdudi', 'MOHAMMED M. A. ALSDUDI'
    UNION ALL SELECT 'Bashar.Abdalbari', 'BASHAR J. F. ABDALBARI'
    UNION ALL SELECT 'Hasan.Alnakhal', 'HASAN D. H. ALNAKHAL'
    UNION ALL SELECT 'Mohamed.Tafish', 'Mohamed Khalid Ibrahim Tafish'
    UNION ALL SELECT 'Oday.Mahdi', 'ODAY A. M. Mahdi'
    UNION ALL SELECT 'Mahmoud.Alkhaldi', 'Mahmoud Tayseer Alkhaldi'
    UNION ALL SELECT 'Hassan.AlJabry', 'Hassan M. H. Al-Jabry'
    UNION ALL SELECT 'Mojahed.Faraht', 'Mojahed Y. SH. Faraht'
    UNION ALL SELECT 'Mohammed.Elhaloul', 'MOHAMMED A. I. ELHALOUL'
    UNION ALL SELECT 'Esraa.AlManasra', 'Esraa Al Manasra'
    UNION ALL SELECT 'Khaled.Al-Daour', 'Khaled Zaki Ebrahim Al-Daour'
    UNION ALL SELECT 'Said.Rehan', 'SAID MJ. A. REHAN'
    UNION ALL SELECT 'Fayez.Abusafia', 'FAYEZ S. A. ABUSAFIA'
    UNION ALL SELECT 'Hussein.Labad', 'Hussein M.H Labad'
    UNION ALL SELECT 'Belal.AbuKhaleifa', 'Belal Mohammed Abed Abu Khaleifa'
    UNION ALL SELECT 'Abed.Yassen', 'Abed Allah Yassen'
    UNION ALL SELECT 'Lamis.Abuzaina', 'LAMIS A. A. ABUZAINA'
    UNION ALL SELECT 'Osama.AboAli', 'Osama Samir khaled abo ali'
    UNION ALL SELECT 'Irahim.Alnajjar', 'IRAHIM J. I. ALNAJJAR'
    UNION ALL SELECT 'Mustafa.Redwan', 'Mustafa M. M. Redwan'
    UNION ALL SELECT 'Eyad.Elwan', 'Eyad S. M. Elwan'
    UNION ALL SELECT 'Ali.Lubbad', 'ALI J. M. LUBBAD'
    UNION ALL SELECT 'Mohammed.Kassab', 'Mohammed Sami Eshaq Kassab'
    UNION ALL SELECT 'Mohanad.Muamar', 'Mohanad Suliman Muamar'
    UNION ALL SELECT 'Mustafa.Baroud', 'Mustafa Ali Mustafa Baroud'
    UNION ALL SELECT 'Emad.Shahada', 'Emad Mahmoud Mohammed Shehada'
    UNION ALL SELECT 'Ibrahim.Alhallaq', 'Ibrahim Kh. Ab. Al-Haalq'
    UNION ALL SELECT 'Ahmed.Muhhana', 'Ahmed Mohammed Abed Alrahmen Muhhana'
    UNION ALL SELECT 'Hasan.Almasri', 'Hassan K. A. Al-Massry'
    UNION ALL SELECT 'Mohammed.Abureaida', 'Mohammed Abu Raida'
    UNION ALL SELECT 'Abeer.Alkaiyaly', 'Abeer Waleed Omar Alkaiyal'
    UNION ALL SELECT 'mohammed.shurafa', 'Mohammed Essam Ahmed'
    UNION ALL SELECT 'Bilal.AbuGhalaa', 'Bilal A.M AbuGhalaa'
    UNION ALL SELECT 'Ahmed.Abudaqqa', 'Ahmed Sh. Ali Abu Daqqa'
    UNION ALL SELECT 'Shrouq.Alrayes', 'SHROUQ N. B. ALRAYES'
    UNION ALL SELECT 'Yassmed.AbuMadallah', 'Yassmed M. M. Abu Madallah'
    UNION ALL SELECT 'Lamyaa.Mousa', 'LAMYAA H. M. MOUSA'
) m ON u.name_en = m.match_name
SET u.username_arcgis = m.assignedto;