<?php

declare(strict_types=1);

namespace App\Support\Forms;

class RoadFacilitySurveyLayout extends StaticSurveyLayout
{
    public static function sections(): array
    {
        return [
            'Root' => [
                'type' => 'group',
                'name' => 'Root',
                'label' => 'Root',
                'hint' => null,
                'fields' => [
                    [
                        'name' => 'location',
                        'type' => 'text',
                        'label' => 'حدود الشارع',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'Field_status',
                        'type' => 'text',
                        'label' => 'Field_status',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'objectid',
                        'type' => 'integer',
                        'label' => 'objectid',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'Governorate',
                        'type' => 'text',
                        'label' => 'المحافظة',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'Municipalitie',
                        'type' => 'text',
                        'label' => 'البلدية',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'Neighborhood',
                        'type' => 'text',
                        'label' => 'الحي',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'AssignedTo',
                        'type' => 'text',
                        'label' => 'اسم الباحث',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'GroupNumber',
                        'type' => 'integer',
                        'label' => 'رقم المجموعة',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'Zone_Code',
                        'type' => 'text',
                        'label' => 'رقم الزون',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'audit',
                        'type' => 'text',
                        'label' => 'audit',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'audit_low',
                        'type' => 'text',
                        'label' => 'audit_low',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'submissionDate',
                        'type' => 'text',
                        'label' => 'submissionDate',
                        'hint' => null,
                        'list_name' => null,
                    ],
                    [
                        'name' => 'other_note',
                        'type' => 'note',
                        'label' => 'ظهرت هذه الصفحة لأنك اخترت الخيار "أخرى" في نوع البنية التحتية المتضررة للطريق. قم بتعبئة بنود مكونات الطريق الأخرى المتضررة في الصفحة التالية. كرر إضافة البنود متى لزم الأمر. من أمثلة المكونات الأخرى: التشجير، إشارات المرور، وكل مكون لم يرد سابقا.',
                        'hint' => null,
                        'list_name' => null,
                    ],
                ],
            ],
            'Introduction' => [
                'type' => 'group',
                'name' => 'Introduction',
                'label' => 'Introduction',
                'hint' => null,
                'fields' => [
                    [
                        'name' => 'Weather',
                        'type' => 'select_one',
                        'label' => 'Weather',
                        'hint' => 'حالة الطقس',
                        'list_name' => 'weather',
                    ],
                    [
                        'name' => 'Security_Situation',
                        'type' => 'select_one',
                        'label' => 'Security Situation',
                        'hint' => 'هل يوجد عائق يمنع عملية الحصر',
                        'list_name' => 'security',
                    ],
                    [
                        'name' => 'security_Info',
                        'type' => 'text',
                        'label' => 'security information',
                        'hint' => 'ما هو العائق',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'Str_Name',
                        'type' => 'text',
                        'label' => '3.1 اسم الشارع',
                        'hint' => 'Road Name',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'Str_No',
                        'type' => 'integer',
                        'label' => '3.2 رقم الشارع',
                        'hint' => 'رقم الشارع حسب ترقيم البلدية',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'closest_facility',
                        'type' => 'text',
                        'label' => '4.5 أقرب معلم',
                        'hint' => 'Closest Facility to Incident',
                        'list_name' => null,
                    ],
                ],
            ],
            'Local_Authority_information' => [
                'type' => 'group',
                'name' => 'Local_Authority_information',
                'label' => '2. Local Authority information',
                'hint' => 'معلومات الهيئة/ المجلس المحلي',
                'fields' => [
                    [
                        'name' => 'local_authority_name',
                        'type' => 'text',
                        'label' => '2.1 اسم الهيئة/المجلس المحلي',
                        'hint' => 'Local Authority name',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'local_authority_representative_name',
                        'type' => 'text',
                        'label' => '2.2 اسم ممثل الهيئة',
                        'hint' => 'Local Authority representative name',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'representative_title',
                        'type' => 'text',
                        'label' => '2.3 صفته',
                        'hint' => 'Representative title',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'rep_mobile_no',
                        'type' => 'text',
                        'label' => '2.4 رقم جواله',
                        'hint' => 'رقم الموبايل. اكتب رقم الموبايل بالشكل التالي: 0592797072',
                        'list_name' => null,
                    ],
                ],
            ],
            'Road_Condition_Accessibility' => [
                'type' => 'group',
                'name' => 'Road_Condition_Accessibility',
                'label' => '3. Road Condition & Accessibility',
                'hint' => 'حالة الطريق وقابلية المرور',
                'fields' => [
                    [
                        'name' => 'road_damage_level',
                        'type' => 'select_one',
                        'label' => '3.1 Overall road damage level',
                        'hint' => 'مستوى الضرر العام للطريق',
                        'list_name' => 'road_damage_level',
                    ],
                    [
                        'name' => 'road_access',
                        'type' => 'select_one',
                        'label' => '3.2 Road access status',
                        'hint' => 'قابلية المرور (حالة الشارع)',
                        'list_name' => 'road_access',
                    ],
                    [
                        'name' => 'blockage_reason',
                        'type' => 'select_multiple',
                        'label' => '3.3 If partially or fully closed, what is the reason?',
                        'hint' => 'إذا كان الشارع مفتوح جزئياً أو مغلق، ما السبب؟',
                        'list_name' => 'blockage_reason',
                    ],
                    [
                        'name' => 'potholes_exist',
                        'type' => 'select_one',
                        'label' => '3.4 Are there potholes that require closure?',
                        'hint' => 'هل يوجد حفر تحتاج إلى إغلاق بالشارع؟',
                        'list_name' => 'yes_no',
                    ],
                    [
                        'name' => 'potholes_count',
                        'type' => 'integer',
                        'label' => '3.4.1 Number of potholes',
                        'hint' => 'عدد الحفر',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'potholes_volume_m3',
                        'type' => 'decimal',
                        'label' => '3.4.2 Estimated potholes volume (m³)',
                        'hint' => 'تقدير حجم الحفر (م³)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'damaged_road_width_m',
                        'type' => 'decimal',
                        'label' => '3.5 Damaged road width (m)',
                        'hint' => 'عرض الشارع المتضرر (م)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'lane_count',
                        'type' => 'select_one',
                        'label' => '3.6 Lane count',
                        'hint' => 'عدد المسارات',
                        'list_name' => 'lane_count',
                    ],
                ],
            ],
            'Road_Items' => [
                'type' => 'group',
                'name' => 'Road_Items',
                'label' => '4. Road Items',
                'hint' => 'عناصر الطريق',
                'fields' => [
                    [
                        'name' => 'road_type_note',
                        'type' => 'note',
                        'label' => '4.1 اختر نوع البنية التحتية للطريق، ثم أدخل البنود ذات العلاقة في الحقول التالية',
                        'hint' => 'Please insert the type of road infrastructure you wan to add. Then add damaged items and their quantities.',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'road_type',
                        'type' => 'select_multiple',
                        'label' => '4.2 مكونات/بنود الطريق المتضررة',
                        'hint' => 'Select Damaged Road Components',
                        'list_name' => 'road_type',
                    ],
                    [
                        'name' => 'other_read_type',
                        'type' => 'text',
                        'label' => '4.3  مكونات/بنود الطريق المتضررة أخرى',
                        'hint' => 'أذكر مكونات/بنود الطريق المتضررة أخرى',
                        'list_name' => null,
                    ],
                ],
            ],
            'Road_Surface' => [
                'type' => 'group',
                'name' => 'Road_Surface',
                'label' => '5. Road Surface',
                'hint' => 'سطح الطريق',
                'fields' => [
                    [
                        'name' => 'asphalt',
                        'type' => 'note',
                        'label' => '5.1 طبقة اسفلتية',
                        'hint' => 'Asphalt',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'no_layers',
                        'type' => 'integer',
                        'label' => '5.1.1 عدد الطبقات',
                        'hint' => 'Number of Asphalt Layers',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'thickness_cm',
                        'type' => 'decimal',
                        'label' => '5.1.2 السمك الإجمالي (سم)',
                        'hint' => 'Thickness (cm)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'area_m2',
                        'type' => 'decimal',
                        'label' => '5.1.3 المساحة المتضررة (م2)',
                        'hint' => 'Area (m2)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'basecoarse',
                        'type' => 'note',
                        'label' => '5.2 طبقة البيسكورس',
                        'hint' => 'Basecoarse Layer',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'no_layers_001',
                        'type' => 'integer',
                        'label' => '5.2.1 عدد الطبقات',
                        'hint' => 'Number of Basecoarse Layers',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'thickness_cm_001',
                        'type' => 'decimal',
                        'label' => '5.2.2 السمك الإجمالي (سم)',
                        'hint' => 'Thickness (cm)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'area_m2_001',
                        'type' => 'decimal',
                        'label' => '5.2.3 المساحة المتضررة (م2)',
                        'hint' => 'Area (m2)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'concrete_m3',
                        'type' => 'decimal',
                        'label' => '5.3 خرسانة مسلحة B250  (م3)',
                        'hint' => 'Concrete B250 (m3)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'sidewalk_interlock_m2',
                        'type' => 'decimal',
                        'label' => '5.4 بلاط انترلوك للشوارع سماكة 8 سم (م2)',
                        'hint' => 'Sidewalk Interlock  (8 cm) (m2)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'sidewalk_damage_type',
                        'type' => 'select_multiple',
                        'label' => '5.5 نوع الضرر في الأرصفة',
                        'hint' => 'Type of sidewalk damage',
                        'list_name' => 'sidewalk_damage_type',
                    ],
                    [
                        'name' => 'street_interlock_m2',
                        'type' => 'decimal',
                        'label' => '5.5.1 بلاط انترلوك للأرصفة 6سم (م2)',
                        'hint' => 'Street Interlock (6 cm) (m2)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'sidewalk_basecourse_m2',
                        'type' => 'decimal',
                        'label' => '5.5.2 مساحة طبقة البيسكورس المتضررة (م²)',
                        'hint' => 'Damaged Base Course Area (m²)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'curbstone_damaged_m',
                        'type' => 'decimal',
                        'label' => '5.6 طول حجر الجبهة المتضرر (م.ط)',
                        'hint' => 'Damaged Curbstone (m)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'curbstone_repair_m',
                        'type' => 'decimal',
                        'label' => '5.6.1 صيانة حجر الجبهة (م.ط)',
                        'hint' => 'Repair of Curbstone (m)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'curbstone_painting_m',
                        'type' => 'decimal',
                        'label' => '5.6.2 دهان حجر الجبهة (م.ط)',
                        'hint' => 'Painting of Curbstone (m)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'unpaved_road_m2',
                        'type' => 'decimal',
                        'label' => '5.7 شوارع ترابية أو  زراعية (م2)',
                        'hint' => 'Unpaved Road (m2)',
                        'list_name' => null,
                    ],
                ],
            ],
            'Road_Lighting' => [
                'type' => 'group',
                'name' => 'Road_Lighting',
                'label' => '6. Road Lighting',
                'hint' => 'إنارة الطريق',
                'fields' => [
                    [
                        'name' => 'lighting_electrical_network',
                        'type' => 'decimal',
                        'label' => '6.1 شبكات كهرباء للإنارة (م.ط)',
                        'hint' => 'Lighting Electrical Network (m)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'lighting_poles',
                        'type' => 'note',
                        'label' => '6.2 أعمدة الإنارة',
                        'hint' => 'Lighting Poles',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'pole_type',
                        'type' => 'select_multiple',
                        'label' => '6.3 نوع العمود',
                        'hint' => 'Wooden Pole',
                        'list_name' => 'pole_type',
                    ],
                    [
                        'name' => 'no_steel_pole',
                        'type' => 'integer',
                        'label' => '6.4 عدد الأعمدة المعدنية',
                        'hint' => 'No. Steel Poles',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'no_wooden_pole',
                        'type' => 'integer',
                        'label' => '6.5 عدد الأعمدة الخشبية',
                        'hint' => 'No. Wooden Poles',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'other_pole',
                        'type' => 'text',
                        'label' => '6.6 في حال اخترت أخرى، حدد نوع العمود',
                        'hint' => 'If Other, Specify',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'no_other_pole',
                        'type' => 'integer',
                        'label' => '6.7 عدد الأعمدة الأخرى',
                        'hint' => 'No. Other Poles',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'lanterns_damaged',
                        'type' => 'select_one',
                        'label' => '6.8 هل فوانيس أعمدة الإنارة متضررة؟',
                        'hint' => 'Are street lighting lanterns damaged?',
                        'list_name' => 'yes_no',
                    ],
                    [
                        'name' => 'lanterns_count',
                        'type' => 'integer',
                        'label' => '6.9 عدد الفوانيس المتضررة',
                        'hint' => 'Number of damaged lanterns',
                        'list_name' => null,
                    ],
                ],
            ],
            'Electricity_Distribution' => [
                'type' => 'group',
                'name' => 'Electricity_Distribution',
                'label' => '7. Electricity Distribution',
                'hint' => 'مكونات شبكة الكهرباء (ضغط عالي/منخفض)',
                'fields' => [
                    [
                        'name' => 'electric_poles_damaged',
                        'type' => 'select_one',
                        'label' => '7.1 هل توجد أعمدة كهرباء متضررة؟',
                        'hint' => 'Are there damaged electricity poles?',
                        'list_name' => 'yes_no',
                    ],
                    [
                        'name' => 'pole_voltage_level',
                        'type' => 'select_one',
                        'label' => '7.1.1 مستوى الجهد',
                        'hint' => 'Voltage level',
                        'list_name' => 'voltage_level',
                    ],
                    [
                        'name' => 'pole_material',
                        'type' => 'select_one',
                        'label' => '7.1.2 نوع العمود',
                        'hint' => 'Type of pole',
                        'list_name' => 'pole_material',
                    ],
                    [
                        'name' => 'electric_poles_count',
                        'type' => 'integer',
                        'label' => '7.1.3 عدد أعمدة الكهرباء المتضررة',
                        'hint' => 'Number of damaged electricity poles',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'transformers_damaged',
                        'type' => 'select_one',
                        'label' => '7.2 هل توجد ترنسات كهرباء متضررة؟',
                        'hint' => 'Are there damaged transformers?',
                        'list_name' => 'yes_no',
                    ],
                    [
                        'name' => 'transformers_count',
                        'type' => 'integer',
                        'label' => '7.2.1 عدد الترنسات المتضررة',
                        'hint' => 'Number of damaged transformers',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'cabinets_exist',
                        'type' => 'select_one',
                        'label' => '7.3 هل توجد كابينات كهرباء أو اتصالات متضررة؟',
                        'hint' => 'Are electricity/telecom cabinets damaged?',
                        'list_name' => 'yes_no',
                    ],
                    [
                        'name' => 'cabinets_count',
                        'type' => 'integer',
                        'label' => '7.3.1 عدد الكابينات المتضررة',
                        'hint' => 'Number of damaged cabinets',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'aerial_cables_exist',
                        'type' => 'select_one',
                        'label' => '7.4 هل توجد كوابل كهرباء هوائية متضررة؟',
                        'hint' => 'Are aerial electricity cables damaged?',
                        'list_name' => 'yes_no',
                    ],
                    [
                        'name' => 'cable_voltage_level',
                        'type' => 'select_one',
                        'label' => '7.4.1 مستوى جهد الكابل',
                        'hint' => 'Cable voltage level',
                        'list_name' => 'voltage_level',
                    ],
                    [
                        'name' => 'aerial_cables_length',
                        'type' => 'decimal',
                        'label' => '7.4.2 طول الكوابل الهوائية المتضررة (م)',
                        'hint' => 'Damaged aerial cable length (m)',
                        'list_name' => null,
                    ],
                ],
            ],
            'Surface_Stormwater_Drainage' => [
                'type' => 'group',
                'name' => 'Surface_Stormwater_Drainage',
                'label' => '8. Surface Stormwater Drainage',
                'hint' => 'عناصر تصريف مياه الأمطار – فوق الأرض',
                'fields' => [
                    [
                        'name' => 'stormwater_inlets_count',
                        'type' => 'integer',
                        'label' => '8.1 عدد مصارف مياه الأمطار المتضررة',
                        'hint' => 'Number of damaged stormwater inlets',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'manhole_covers_missing',
                        'type' => 'integer',
                        'label' => '8.2 عدد أغطية المناهل المفقودة أو المكسورة',
                        'hint' => 'Number of missing or broken manhole covers',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'surface_channels_length',
                        'type' => 'decimal',
                        'label' => '8.3 طول قنوات تصريف سطحية متضررة (متر طولي)',
                        'hint' => 'Damaged surface drainage channels length (m)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'water_ponding',
                        'type' => 'select_one',
                        'label' => '8.4 هل يوجد تجمع مياه بسبب الضرر؟',
                        'hint' => 'Is there water ponding due to damage?',
                        'list_name' => 'yes_no',
                    ],
                ],
            ],
            'Traffic_Signs_Road_Furniture' => [
                'type' => 'group',
                'name' => 'Traffic_Signs_Road_Furniture',
                'label' => '9. Traffic Signs & Road Furniture',
                'hint' => 'الإشارات المرورية',
                'fields' => [
                    [
                        'name' => 'traffic_signs_type',
                        'type' => 'select_multiple',
                        'label' => '9.1 نوع الإشارات المرورية المتضررة',
                        'hint' => 'Type of damaged traffic signs',
                        'list_name' => 'traffic_signs_type',
                    ],
                    [
                        'name' => 'traffic_signs_count',
                        'type' => 'integer',
                        'label' => '9.2 عدد الإشارات المرورية المتضررة',
                        'hint' => 'Number of damaged traffic signs',
                        'list_name' => null,
                    ],
                ],
            ],
            'Demolition_Works' => [
                'type' => 'group',
                'name' => 'Demolition_Works',
                'label' => '10. Demolition Works',
                'hint' => 'أعمال الإزالة',
                'fields' => [
                    [
                        'name' => 'demolition_scope',
                        'type' => 'select_one',
                        'label' => '10.1 نطاق الإزالة',
                        'hint' => 'Demolition scope',
                        'list_name' => 'demolition_type',
                    ],
                    [
                        'name' => 'demolish_asphalt_m2',
                        'type' => 'decimal',
                        'label' => '10.2 إزالة طبقة الإسفلت (م²)',
                        'hint' => 'Demolish asphalt layer (m²)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'demolish_base_m2',
                        'type' => 'decimal',
                        'label' => '10.3 إزالة طبقة البيسكورس (م²)',
                        'hint' => 'Demolish base course (m²)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'demolish_subbase_m2',
                        'type' => 'decimal',
                        'label' => '10.4 إزالة طبقة السوب بيس (م²)',
                        'hint' => 'Demolish subbase layer (m²)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'obstacle_exist',
                        'type' => 'select_one',
                        'label' => '10.5 هل توجد عوائق تعترض الطريق؟',
                        'hint' => 'Are there obstacles blocking the road?',
                        'list_name' => 'yes_no',
                    ],
                    [
                        'name' => 'obstacle_type',
                        'type' => 'text',
                        'label' => '10.5.1 نوع العائق',
                        'hint' => 'Type of obstacle',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'obstacle_volume_m3',
                        'type' => 'decimal',
                        'label' => '10.5.2 حجم العائق (م³)',
                        'hint' => 'Obstacle volume (m³)',
                        'list_name' => null,
                    ],
                ],
            ],
            'Sidewalk_Handrails' => [
                'type' => 'group',
                'name' => 'Sidewalk_Handrails',
                'label' => '11.Sidewalk Handrails',
                'hint' => 'الدرابزين الخاص بالأرصفة',
                'fields' => [
                    [
                        'name' => 'handrails_damaged_mr',
                        'type' => 'decimal',
                        'label' => '11.1 طول الدرابزين المتضرر (م طولي)',
                        'hint' => 'Damaged handrails length (m.l.)',
                        'list_name' => null,
                    ],
                ],
            ],
            'Road_Painting_Works' => [
                'type' => 'group',
                'name' => 'Road_Painting_Works',
                'label' => '12. Road Painting Works',
                'hint' => 'أعمال دهانات الطرق',
                'fields' => [
                    [
                        'name' => 'road_painting_m2',
                        'type' => 'decimal',
                        'label' => '12.1 دهانات الطريق (م²)',
                        'hint' => 'Road painting (m²)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'curbstone_painting_mr',
                        'type' => 'decimal',
                        'label' => '12.2 دهان البردورة (م طولي)',
                        'hint' => 'Curbstone painting (m.l.)',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'handrails_painting_mr',
                        'type' => 'decimal',
                        'label' => '12.3 دهان الدرابزين (م طولي)',
                        'hint' => 'Handrails painting (m.l.)',
                        'list_name' => null,
                    ],
                ],
            ],
            'R2' => [
                'type' => 'repeat',
                'name' => 'R2',
                'label' => '13. بند آخر',
                'hint' => null,
                'fields' => [
                    [
                        'name' => 'item_required',
                        'type' => 'text',
                        'label' => '13.1 البند المطلوب',
                        'hint' => 'Item required',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'description',
                        'type' => 'text',
                        'label' => '13.2 وصف البند',
                        'hint' => 'Description',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'unit_001',
                        'type' => 'select_one',
                        'label' => '13.3 الوحدة',
                        'hint' => 'Unit',
                        'list_name' => 'unit',
                    ],
                    [
                        'name' => 'quantity_001',
                        'type' => 'integer',
                        'label' => '13.4 الكمية',
                        'hint' => 'Quantity',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'other_comments',
                        'type' => 'text',
                        'label' => '13.5 ملاحظات على البند',
                        'hint' => 'comments',
                        'list_name' => null,
                    ],
                ],
            ],
            'safety_sensitive_observations' => [
                'type' => 'group',
                'name' => 'safety_sensitive_observations',
                'label' => '14. Safety & Sensitive Observations',
                'hint' => 'ملاحظات السلامة والمخاطر',
                'fields' => [
                    [
                        'name' => 'buried_bodies',
                        'type' => 'select_one',
                        'label' => '14.1 هل يوجد جثث مدفونة بالشارع؟',
                        'hint' => 'Are there buried bodies on the road?',
                        'list_name' => 'yes_no',
                    ],
                    [
                        'name' => 'buried_bodies_est',
                        'type' => 'integer',
                        'label' => '14.1.1 العدد التقديري للجثث',
                        'hint' => 'Estimated number of buried bodies',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'uxo_present',
                        'type' => 'select_one',
                        'label' => '14.2 هل يوجد ذخائر غير منفجرة بالشارع؟',
                        'hint' => 'Are there unexploded ordnance (UXO) on the road?',
                        'list_name' => 'yes_no',
                    ],
                ],
            ],
            'photos_final_comments' => [
                'type' => 'group',
                'name' => 'photos_final_comments',
                'label' => '15. Photos & Final Comments',
                'hint' => 'الصور والملاحظات النهائية',
                'fields' => [
                    [
                        'name' => 'damge_photo_1',
                        'type' => 'image',
                        'label' => '15.1 خذ صورة للمرفق المتضرر',
                        'hint' => 'Take a photo for the damaged unit',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'damge_photo_2',
                        'type' => 'image',
                        'label' => '15.2 خذ صورة أخرى',
                        'hint' => 'Take another photo for the damaged unit',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'damge_photo_3',
                        'type' => 'image',
                        'label' => '15.3خذ صورة ثالثة',
                        'hint' => 'Take a third photo for the damaged unit',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'damge_photo_4',
                        'type' => 'image',
                        'label' => '15.4خذ صورة رابعة',
                        'hint' => 'Take a third photo for the damaged unit',
                        'list_name' => null,
                    ],
                    [
                        'name' => 'final_comments',
                        'type' => 'text',
                        'label' => '15.5 الملاحظات والتوصيات النهائية من قبل الماسح',
                        'hint' => 'Final Comments and Recommendations',
                        'list_name' => null,
                    ],
                ],
            ],
        ];
    }

    public static function choices(): array
    {
        return [
            'yes_no' => [
                'yes' => 'Yes',
                'no' => 'No',
            ],
            'security' => [
                'Safe' => 'لا يوجد عائق',
                'Unsafe' => 'يوجد عائق',
            ],
            'infra_type' => [
                'water_network' => 'Water network',
                'sewer_network' => 'Sewer network',
                'storm_water_network' => 'Storm water network',
                'water_well' => 'Water Well',
                'water_desalination_plant' => 'Water desalination plant',
                'water_reservoirs' => 'Water reservoirs',
                'wwtp' => 'WWTP',
                'water_pumping_station' => 'Water Pumping station',
                'sewage_pumping_station' => 'Sewage Pumping station',
                'storm_water_pumping_station' => 'Storm water pumping station',
                'solid_waste_transfer_station' => 'Solid waste transfer station',
                'cmwu_stores' => 'CMWU Stores',
                'other_infra' => 'Other (Specify)',
            ],
            'governorate' => [
                'North' => 'North',
                'Gaza' => 'Gaza',
                'Middle_Area' => 'Middle Area',
                'Khan_Younis' => 'Khan Younis',
                'Rafah' => 'Rafah',
            ],
            'locality' => [
                'Um_AlNasser' => 'Um_AlNasser',
                'Bait_Hanoun' => 'Bait_Hanoun',
                'Jabalia' => 'Jabalia',
                'Bait_Lahia' => 'Bait_Lahia',
                'Gaza' => 'Gaza',
                'Juhr_Aldeek' => 'Juhr_Aldeek',
                'Almughraqa' => 'Almughraqa',
                'Alzahra' => 'Alzahra',
                'AlNusairat' => 'AlNusairat',
                'Alburaje' => 'Alburaje',
                'AlMaghazi' => 'AlMaghazi',
                'AlMusadar' => 'AlMusadar',
                'Wadi_Alsalqa' => 'Wadi_Alsalqa',
                'Dair_Albalah' => 'Dair_Albalah',
                'Alzawayda' => 'Alzawayda',
                'Khanyounis' => 'Khanyounis',
                'Alqarara' => 'Alqarara',
                'Bani_Sohaila' => 'Bani_Sohaila',
                'Abasan_AlJadida' => 'Abasan_AlJadida',
                'Abasan_alkabeira' => 'Abasan_alkabeira',
                'Khuzaa' => 'Khuzaa',
                'AlFukhari' => 'AlFukhari',
                'Rafah' => 'Rafah',
                'AlNasser' => 'AlNasser',
                'AlShuka' => 'AlShuka',
            ],
            'type_damage' => [
                'Completely' => 'Completely',
                'partially' => 'Partially',
            ],
            'weather' => [
                'fine' => 'Fine',
                'windy' => 'Windy',
                'rainy' => 'Rainy',
            ],
            'damage_cause' => [
                'direct_attack' => 'Direct attack',
                'indirect_attack' => 'Indirect attack',
                'other_cause' => 'Other (specify)',
            ],
            'unit' => [
                'cube_meter__m3' => 'Cube Meter (m3)',
                'square_meter__m2' => 'Square Meter (m2)',
                'run_meter__m' => 'Run Meter (m)',
                'liter' => 'Liter',
                'no' => 'No.',
                'kilogram__kg' => 'Kilogram (Kg)',
                'ton__t' => 'Ton (t)',
                'other_unit' => 'Other',
            ],
            'provider_response' => [
                'none' => 'None',
                'temporary_repairs' => 'Temporary repairs',
                'permanent_repairs' => 'Permanent repairs',
            ],
            'pipe_type' => [
                'steel' => 'Steel',
                'concrete' => 'Concrete',
                'upvc' => 'UPVC',
                'hdpe' => 'HDPE',
                'ductile_iron' => 'Ductile iron',
                'other_pipe' => 'Other (specify)',
            ],
            'fittings' => [
                'control_valve' => 'Control valve',
                'magnetic_valve' => 'Magnetic Valve',
                'water_meter' => 'Water meter',
                'elbow' => 'Elbow',
                'strainer' => 'Strainer',
                'pressure_reducing_valve' => 'Pressure Reducing Valve',
                'air_release_valve' => 'Air Release Valve',
                'water_manhole' => 'Water Manhole',
                'sewer_manhole' => 'Sewer Manhole',
                'storm_water_manhole' => 'Storm water Manhole',
                'storm_water__culvert' => 'Storm water  culvert',
                'other_fittings' => 'Other (Specify)',
            ],
            'reinstatement_type' => [
                'asphalt' => 'Asphalt',
                'tiles' => 'Tiles',
                'dirt_road' => 'Dirt road',
                'other_reinstatement' => 'Other (Specify)',
            ],
            'road_type' => [
                'asphalt' => 'Asphalt طبقة أسفلتية',
                'basecoarse' => 'basecoarse طبقة بيسكورس',
                'concrete' => 'Concrete خرسانة',
                'street_interlock' => 'Street Interlock انترلوك للشوارع',
                'sidewalk_interlock' => 'Sidewalk الأرصفة',
                'curbstone' => 'Curbstone حجر جبهة',
                'unpaved_road' => 'Unpaved Road شارع ترابي أو زراعي',
                'lighting_electrical_network' => 'Lighting Electrical Network شبكة كهرباء للإنارة',
                'lighting_poles' => 'Lighting Poles أعمدة كهرباء للإنارة',
                'electricity_distribution_network' => 'شبكة الكهرباء (ضغط عالي/منخفض) Electricity distribution network',
                'stormwater' => 'Surface stormwater drainage مصارف مياه الأمطار',
                'traffic_signs' => 'Traffic signs & road furniture الإشارات المرورية',
                'demolition_works' => 'Demolition Works أعمال الإزالة',
                'Handrails' => 'Handrails الدرابزين',
                'road_painting' => 'Road Painting أعمال دهانات الطرق',
                'other_component' => 'Other أخرى',
            ],
            'pole_type' => [
                'wooden_pole' => 'Wooden Pole عمود خشبي',
                'steel_pole' => 'Steel Pole عمود معدني',
                'other_pole' => 'Other أخرى',
            ],
            'network_type' => [
                'water_network' => 'Water Network شبكة مياه',
                'sewage_network' => 'Sewage Network شبكة صرف صحي',
                'storm_water' => 'Storm Water Network شبكة تصريف مياه أمطار',
            ],
            'network_item' => [
                'pipe' => 'Pipe',
                'fittings' => 'Fittings',
                'reinstatement' => 'Reinstatement Works',
            ],
            'road_damage_level' => [
                'minor' => 'Minor damage (road usable)',
                'moderate' => 'Moderate damage (partial use / needs maintenance)',
                'severe' => 'Severe damage (not usable)',
                'destroyed' => 'Totally destroyed',
                'No_Damage' => 'No Damage',
            ],
            'road_access' => [
                'open' => 'Fully open',
                'partial' => 'Partially open',
                'closed' => 'Fully closed',
            ],
            'blockage_reason' => [
                'landfill' => 'Backfill / excavation',
                'debris' => 'Debris / rubble',
                'poles' => 'Fallen poles',
                'uxo' => 'Security risk (UXO)',
            ],
            'lane_count' => [
                'one' => 'One lane',
                'two' => 'Two lanes',
                'more' => 'More than two',
            ],
            'sidewalk_damage_type' => [
                'broken_tiles' => 'Broken tiles',
                'missing_tiles' => 'Missing tiles',
                'collapsed_sidewalk' => 'Collapsed sidewalk',
                'pwd_ramps_damaged' => 'Damaged accessibility ramps',
                'pedestrian_obstacles' => 'Pedestrian obstacles',
            ],
            'traffic_signs_type' => [
                'guide' => 'Guide signs',
                'warning' => 'Warning signs',
                'traffic_light' => 'Traffic lights',
                'mirrors' => 'Intersection mirrors',
                'speed_bumps' => 'Speed bumps',
                'other' => 'Other',
            ],
            'demolition_type' => [
                'whole' => 'Whole',
                'partial' => 'Partially',
                'no_need' => 'No need',
            ],
            'pole_material' => [
                'galvanized' => 'Galvanized steel pole',
                'wooden' => 'Wooden pole',
            ],
            'voltage_level' => [
                'low' => 'Low voltage',
                'high' => 'High voltage',
            ],
        ];
    }
}
