<?php

test('audit table keeps all columns with responsive text cells', function () {
    $view = file_get_contents(dirname(__DIR__, 2).'/app/Modules/DamageAssessment/views/audit/audit.blade.php');
    $controller = file_get_contents(dirname(__DIR__, 2).'/app/Modules/DamageAssessment/Http/Controllers/Audit/auditController.php');
    $exportService = file_get_contents(dirname(__DIR__, 2).'/app/Modules/DamageAssessment/Services/Audit/AuditExportService.php');

    expect($view)
        ->toContain('audit-table-wrapper')
        ->toContain('audit-cell-text')
        ->toContain('renderAuditTextCell')
        ->toContain('renderAuditLtrCell')
        ->toContain('audit-cell-date')
        ->toContain('autoWidth: false')
        ->toContain('scrollX: true')
        ->toContain('responsive: false')
        ->toContain('ordering: false')
        ->toContain("targets: '_all'")
        ->toContain('width: 100% !important')
        ->toContain('min-width: 940px')
        ->toContain('table-layout: fixed')
        ->toContain('padding: 0.45rem 0.35rem')
        ->toContain('#kt_datatable_audits_wrapper table.dataTable thead th.sorting::before')
        ->toContain('background-image: none !important')
        ->toContain('.dt-column-order')
        ->toContain('font-size: 0.74rem')
        ->toContain("#kt_datatable_audits tbody td {\n\t\t\tfont-size: 1rem;")
        ->not->toContain('font-size: .1rem')
        ->toContain('audit-select-cell')
        ->toContain('audit-actions-cell')
        ->toContain('float: none !important')
        ->toContain('#kt_datatable_audits_wrapper table.dataTable .audit-select-cell')
        ->toContain('position: absolute')
        ->toContain('left: 50%')
        ->toContain('top: 50%')
        ->toContain('transform: translate(-50%, -50%) !important')
        ->toContain("width: '64px'")
        ->toContain("width: '16%'")
        ->toContain("width: '8%'")
        ->toContain("width: '12%'")
        ->toContain("width: '9%'")
        ->toContain("width: '11%'")
        ->toContain("width: '10%'")
        ->toContain('table.columns.adjust()')
        ->toContain('overflow-x: auto')
        ->toContain('auditExportModal')
        ->toContain('auditExportForm')
        ->toContain("route('audit.export')")
        ->toContain('notes_history')
        ->toContain('no_notes_history')
        ->toContain('notesHistory')
        ->toContain('escapeAuditCell(item.notes)')
        ->toContain('btn-building-attachments')
        ->toContain('buildingAttachmentsModal')
        ->toContain('معاينة')
        ->toContain('renderAttachmentPreview')
        ->toContain('isImageAttachment')
        ->toContain('object-fit-cover')
        ->toContain("route('audit.building.attachments.index'")
        ->toContain("route('audit.building.attachments.store'")
        ->toContain("route('audit.building.attachments.replace'")
        ->toContain("route('audit.building.attachments.destroy'")
        ->toContain('building_columns[]')
        ->toContain('housing_columns[]')
        ->toContain('toggle_select_column')
        ->toContain('const selectColumn = table.column(0)')
        ->toContain('visible: false')
        ->toContain('$isFieldEngineerAudit')
        ->toContain("route('audit.fieldEngineer')");

    expect($controller)
        ->toContain('show_all_notes')
        ->toContain('buildingAttachments')
        ->toContain('storeBuildingAttachment')
        ->toContain('replaceBuildingAttachment')
        ->toContain('destroyBuildingAttachment')
        ->toContain('ArcgisAttachmentBackupService')
        ->toContain('backupBuildingAttachment($building, $attachmentId, \'replace\'')
        ->toContain('backupBuildingAttachment($building, $attachmentId, \'delete\'');

    expect($exportService)
        ->toContain('public function buildingColumns(): array')
        ->toContain('public function housingColumns(): array')
        ->toContain("'governorate' =>")
        ->toContain("'municipality' =>")
        ->toContain("'neighborhood' =>")
        ->toContain('building_status_notes')
        ->toContain('housing_status_notes');
});

test('assessment audit inline edits resolve missing global ids before saving', function () {
    $view = file_get_contents(dirname(__DIR__, 2).'/app/Modules/DamageAssessment/views/audit/assessmentAudit.blade.php');

    expect($view)
        ->toContain('overflow: visible')
        ->not->toContain('audit-sticky-menu .audit-sticky-menu')
        ->toContain('function resolveInlineGlobalId')
        ->toContain("type === 'building_table'")
        ->toContain("type === 'housing_table'")
        ->toContain('let isAssessmentReadOnly')
        ->toContain('!isAreaManager && !isAssessmentReadOnly')
        ->toContain('يرجى اختيار الوحدة أولاً');
});
